// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 1
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){













var cb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var db=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,eb=function(a){if(null==a)return String(a);var b=db.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},fb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Na=function(a){if(!a||"object"!=eb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!fb(a,"constructor")&&!fb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||fb(a,b)},gb=function(a,b){var c=b||("array"==eb(a)?[]:{}),d;for(d in a)if(fb(a,d)){var e=a[d];"array"==eb(e)?("array"!=eb(c[d])&&(c[d]=[]),c[d]=gb(e,c[d])):Na(e)?(Na(c[d])||(c[d]={}),c[d]=gb(e,c[d])):c[d]=e}return c};var Ra=null,hb=Math.random(),ib=null,Ga=null,Za=!1,jb={},kb={},$a={};var lb,mb,nb,ob,pb,qb,rb,sb,ub,vb,wb,xb,S,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Mb,Nb,Ob,Pb,Qb,Rb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,U,ed,fd,gd,hd,id,jd,kd,ld,md,nd,qd,rd,sd,td,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,
ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf;
(function(){var a=function(a){return{toString:function(){return a}}};lb=a("");mb=a("");nb="";ob=a("");pb=a("");qb=a("");rb=a("");sb=a("");ub=a("");vb=a("");wb=a("");xb=a("");S=a("");yb=a("");zb=a("");Ab=a("");
Bb=a("");Cb=a("");Db=a("");Eb=a("");Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");Kb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");
Qb=a("");Rb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("0");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");
hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");
yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");
Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("1");Zc=a("");$c=a("4");ad=a("5");bd=a("");cd=a("");dd=a("");
U=a("");ed=a("");fd=a("");gd=a("");hd=a("");id=a("2");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");qd=a("");rd=a("");sd=a("");td=a("");wd=a("");xd=a("");yd=a("");zd=a("");Ad=
a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("3");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");
Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");
me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=
a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");
Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe="";Ye=a("");Ze=a("");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=
a("");kf=a("");lf=a("");mf=a("");nf=a("")})();var of=function(){},O=function(a){return"function"==typeof a},xa=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},pf=function(a){return"number"==eb(a)&&!isNaN(a)},qf=function(a){return/^[0-9]+$/.test(a)},rf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Fa=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},K=function(a){return Math.round(Number(a))||0},Ha=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},sf=function(a){var b=[];if(xa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},H=function(){return new Date},Ja=function(a,b){if(!pf(a)||!pf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},tf=function(){this.prefix="gtm.";this.values={}};tf.prototype.set=function(a,b){this.values[this.prefix+a]=b};tf.prototype.get=function(a){return this.values[this.prefix+a]};tf.prototype.contains=function(a){return void 0!==this.get(a)};
var Af=function(a,b,c){try{if(!a[Cd])return a[Yc](a,b||of,c||of);c&&c()}catch(d){}return!1},Bf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=Fa(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Cf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Df=function(a){return function(){return a("GTM-PN2MP4")}},Ef=function(a){for(var b=0;b<a.length;b++)a[b]()},Ff=H().getTime(),Ma=function(){return"gtm"+
Ff++},Oa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Gf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},If=function(a,b){0==b?a.Wa=!0:a.complete=!0;var c=a.g;a.s&&(a.s.Ha[c]=b);jb[c]&&(jb[c].state=b)},Jf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var w=window,J=document,Lf=navigator,Q=function(a,b){var c=w[a];w[a]=void 0===c?b:c;return w[a]},I=function(a,b,c,d){return(d||"http:"!=w.location.protocol?a:b)+c},Mf=function(a){var b=J.getElementsByTagName("script")[0]||J.body||J.head;b.parentNode.insertBefore(a,b)},Qa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,c){var d=J.createElement("script");d.type="text/javascript";d.async=
!0;d.src=a;Qa(d,b);c&&(d.onerror=c);Mf(d);return d},ga=function(a,b){var c=J.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Mf(c);Qa(c,b);void 0!==a&&(c.src=a);return c},G=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},L=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},x=function(a){w.setTimeout(a,0)},Ta=!1,
Ua=[],Nf=function(a){if(!Ta){var b=J.createEventObject,c="complete"==J.readyState,d="interactive"==J.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Ta=!0;for(var e=0;e<Ua.length;e++)Ua[e]()}Ua.push=function(){for(var a=0;a<arguments.length;a++)x(arguments[a]);return 0}}},Of=0,Pf=function(){if(!Ta&&140>Of){Of++;try{J.documentElement.doScroll("left"),Nf()}catch(a){w.setTimeout(Pf,50)}}},ya=function(a){var b=J.getElementById(a);if(b&&sa(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(sa(document.all[a][c],
"id")==a)return document.all[a][c];return b},sa=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},va=function(a){return a.target||a.srcElement||{}},Ea=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Xa=function(a){var b=J.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},
wa=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Qf=!1,Rf=[],Sf=function(){if(!Qf){Qf=!0;for(var a=0;a<Rf.length;a++)Rf[a]()}},Tf=function(a){a=a||w;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},Va=function(a){window.console&&window.console.log&&window.console.log(a)};var aa=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||w.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||w.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:w.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=rf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),l=0;l<m.length;l++){var p=m[l].split("=");if(decodeURIComponent(p[0]).replace(/\+/g," ")==e){f=decodeURIComponent(p.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Uf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ba=function(a){var b=
J.createElement("a");a&&(b.href=a);return b};var ia=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var fa=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=aa(ba(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},Ba=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};var Vf=new tf,Wf={},Yf={set:function(a,b){gb(Xf(a,b),Wf)},get:function(a){return P(a,2)},reset:function(){Vf=new tf;Wf={}}},P=function(a,b){if(2==b){for(var c=Wf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Vf.get(a)},Xf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Zf=Math.random(),$f="0.100000">Zf;var ag=function(a,b){$f&&G("//www.googletagmanager.com/a?id=GTM-PN2MP4&cv=1&v=t&n="+a+(void 0!==b?"&s="+encodeURIComponent(b):"")+"&l="+(H().getTime()-K(ib))+"&sr=0.100000&ps="+Zf+"&cb="+Ja());},bg=of;var cg=of,dg=[],eg=!1,ca=function(a){return w["dataLayer"].push(a)},fg=function(a){var b=!1;return function(){!b&&O(a)&&x(Df(a));b=!0}},lg=function(){for(var a=!1;!eg&&0<dg.length;){eg=!0;var b=dg.shift();if(O(b))try{b.call(Yf)}catch(za){}else if(xa(b))a:{var c=b;if("string"==eb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Wf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(za){}}}else{var k=void 0,m=void 0,l=b;for(m in l)if(l.hasOwnProperty(m)){var p=
m,q=l[m];Vf.set(p,q);gb(Xf(p,q),Wf)}var v=!1,y=l.event;if(y){k=Ff++;Ga=y;if(!l["gtm.uniqueEventId"]){var t=k;Vf.set("gtm.uniqueEventId",t);gb(Xf("gtm.uniqueEventId",t),Wf)}var z=fg(l.eventCallback),E=l.eventTimeout;E&&w.setTimeout(z,Number(E));v=cg(k,y,z,l.eventReporter)}ib||(ib=l["gtm.start"])&&bg();var D=l,C=k,A=y,M=Wf;if(!v){var F=k,N=y;}Ga=null;a=v||a}var T=b,R=Wf;kg();eg=!1}return!a},mg=function(){var a=lg();try{var b=w["dataLayer"].hide;if(b&&void 0!==b["GTM-PN2MP4"]&&b.end){b["GTM-PN2MP4"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a};var ua=function(a,b,c){L(a,b,c,void 0)},ea=function(a,b,c){r(a,b,c)},ab=function(a,b){w[a]=b},n=function(a,b,c){var d=w;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},u=function(a,b,c){return("https:"==w.location.protocol?a:b)+c};var ng=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),og={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},pg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},qg=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},rg=function(){var a=P("gtm.whitelist");
var b=a&&qg(sf(a),og),c=P("gtm.blacklist")||P("tagTypeBlacklist")||[];ng.test(w.location&&w.location.hostname)&&(c=sf(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&qg(sf(c),pg),e={};return function(f){var g=f&&f[Yc];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>rf(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>rf(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var l;if(!(l=0<=rf(d,g.a)))a:{for(var p=g.b||[],q=new tf,v=0;v<d.length;v++)q.set(d[v],!0);for(v=0;v<p.length;v++)if(q.get(p[v])){l=!0;break a}l=!1}m=l}return e[g.a]=!h||m}};var Da=function(a){var b=J;return sg?b.querySelectorAll(a):null},tg=!1;if(J.querySelectorAll)try{var ug=J.querySelectorAll(":root");ug&&1==ug.length&&ug[0]==J.documentElement&&(tg=!0)}catch(a){}var sg=tg;var vg=void 0,wg="",xg=0,yg=void 0,_et=function(a){var b,c=P("gtm.element"),d=P("event"),e=Number(H());vg===c&&wg===d&&xg>e-250?b=yg:(yg=b=c?Ea(c):"",vg=c,wg=d);xg=e;return b?b:a[vc]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(P("gtm.elementUrl")||a[vc]||""),c=ba(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Ga};_e.a="e";_e.b=["google"];var zg=/(^|\.)doubleclick\.net$/i,Ag=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ia=function(a){for(var b=String(J.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=Fa(e[0]);if(f&&f==a){var g=Fa(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},Bg=function(a,b,c,d,e){if(zg.test(J.location.hostname)||"/"==c&&Ag.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=J.cookie;J.cookie=f;return g!=
J.cookie||0<=rf(Ia(a),b)},Cg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Dg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Eg=function(){var a=aa(w.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var Fg=function(a,b){this.f=a;this.j=b};Fg.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var Gg=function(a,b){this.Fa=a;this.ka=b};Gg.prototype.toString=function(){return""+this.ka+"."+this.Fa};var Jg=function(a,b){var c=new Hg(null,a,b);Ig(c);return c},Hg=function(a,b,c){this.Oa=Math.floor(H().getTime()/864E5);this.ja=b||"auto";this.aa=c||"/";var d=Cg(this.ja),e=Dg(this.aa);this.F=a||new Fg(d,e);this.h=[];this.C=new tf},Lg=function(a,b,c){b&&(""==c.Fa?Kg(a,b):(a.C.contains(b)||a.h.push(b),a.C.set(b,c)))},Mg=function(a,b){for(var c=0;c<b.length;c++)Lg(a,b[c][0],b[c][1])},Kg=function(a,b){var c=rf(a.h,b);0<=c&&a.h.splice(c,1);a.C.set(b,void 0)},Ng=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.C.get(d)])}return b},Og=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.C.get(a.h[c]).ka);return 864E5*b};Hg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.C.get(c).toString())}return"GAX1."+this.F.toString()+"."+a.join("!")};
var Pg=function(a,b){for(var c=new Date,d=Dg(a.aa),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.C.get(g).ka<a.Oa&&e.push(g)}for(f=0;f<e.length;f++)Kg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(Og(a));if("auto"!=a.ja)return Bg("_gaexp",a.toString(),a.aa,a.ja,c);for(var h=Eg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.F=new Fg(Cg(h[k]),d),Bg("_gaexp",a.toString(),a.aa,h[k],c)))return!0;return!1},Ig=function(a){for(var b=a.F.f,c=a.F.j,d=Ia("_gaexp"),e=[],f=0;f<d.length;f++){var g=Qg(a,d[f]);g&&e.push(g)}Jf(e,
function(a,d){var e=a.F,f=d.F;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.F=0<e.length?e[0].F:new Fg(b,c);for(f=e.length-1;0<=f;f--)Mg(a,Ng(e[f]))},Qg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Fa(e[0]);if(0!=f.length){var g=2==e.length?Fa(e[1]):"1";if(qf(f)&&qf(g)){d=new Fg(K(f),K(g));
break a}}}d=void 0}if(d){for(var h=new Hg(d,a.ja,a.aa),k=(c[2]||"").split("!"),m=0;m<k.length;m++){var l=k[m].split(".");if(3==l.length){if(!qf(l[1]))return;Lg(h,l[0],new Gg(l[2],K(l[1])))}}return h}}};var _v=function(a){var b=P(a[Id].replace(/\\\./g,"."),a[nc]);return void 0!==b?b:a[vc]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(P("gtm.referrer")||J.referrer);if(!b)return b;var c=ba(b);return b};_f.a="f";_f.b=["google"];var Ca=function(a){var b=w.location,c;(c=a[kc]?a[kc]:P("gtm.url"))&&(b=ba(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Xb]&&(f=aa(b,a[Xb],a[ue],a[uc],a[he]));return f},_u=Ca;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[xb])==String(a[S])};_eq.a="eq";_eq.b=["google"];var La=new String("undefined"),ch=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===La?b:a[d]);return c.join("")}};ch.prototype.toString=function(){return this.resolve("undefined")};ch.prototype.valueOf=ch.prototype.toString;var dh={},eh=function(a,b){var c=Ff++;dh[c]=[a,b];return c},fh=function(a){var b=a?0:1;return function(a){var c=dh[a];if(c&&O(c[b]))c[b]();dh[a]=void 0}};var gh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},hh=function(a,b){return a<b?-1:a>b?1:0};var ih;a:{var jh=cb.navigator;if(jh){var kh=jh.userAgent;if(kh){ih=kh;break a}}ih=""}var W=function(a){return-1!=ih.indexOf(a)};var lh=function(){W("iPod")},mh=function(){return W("iPhone")&&!W("iPod")&&!W("iPad")};var nh=function(a){nh[" "](a);return a};nh[" "]=function(){};var ph=function(a,b){var c=oh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var qh=W("Opera"),rh=W("Trident")||W("MSIE"),sh=W("Edge"),th;if(th=W("Gecko"))th=!(-1!=ih.toLowerCase().indexOf("webkit")&&!W("Edge"));var uh=th&&!(W("Trident")||W("MSIE"))&&!W("Edge"),vh=-1!=ih.toLowerCase().indexOf("webkit")&&!W("Edge");vh&&W("Mobile");W("Macintosh");W("Windows");W("Linux")||W("CrOS");var wh=cb.navigator||null;wh&&(wh.appVersion||"").indexOf("X11");W("Android");mh();W("iPad");lh();mh()||W("iPad")||lh();var xh=function(){var a=cb.document;return a?a.documentMode:void 0},yh;
a:{var zh="",Ah=function(){var a=ih;if(uh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(sh)return/Edge\/([\d\.]+)/.exec(a);if(rh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(vh)return/WebKit\/(\S+)/.exec(a);if(qh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ah&&(zh=Ah?Ah[1]:"");if(rh){var Bh=xh();if(null!=Bh&&Bh>parseFloat(zh)){yh=String(Bh);break a}}yh=zh}
var Ch=yh,oh={},Dh=function(a){return ph(a,function(){for(var b=0,c=gh(String(Ch)).split("."),d=gh(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],m=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==m[0].length)break;b=hh(0==k[1].length?0:parseInt(k[1],10),0==m[1].length?0:parseInt(m[1],10))||hh(0==k[2].length,0==m[2].length)||hh(k[2],m[2]);g=k[3];h=m[3]}while(0==b)}return 0<=b})},Eh;
var Fh=cb.document;Eh=Fh&&rh?xh()||("CSS1Compat"==Fh.compatMode?parseInt(Ch,10):5):void 0;var Gh;if(!(Gh=!uh&&!rh)){var Hh;if(Hh=rh)Hh=9<=Number(Eh);Gh=Hh}Gh||uh&&Dh("1.9.1");rh&&Dh("9");var Wa=function(a,b){var c="";rh&&!Ih(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Jh)a.srcdoc=d;else if(Kh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Lh(a,d)},Jh=vh&&"srcdoc"in document.createElement("iframe"),Kh=uh||vh||rh&&Dh(11),Lh=function(a,b){rh&&Dh(7)&&!Dh(10)&&6>Mh()&&Nh(b)&&(b=Oh(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};rh&&!Ih(a)?Ph(a,c):c()},Mh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Ih=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{nh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Qh=0,Ph=function(a,b){var c="goog_rendering_callback"+Qh++;cb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Nh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Oh=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var fi=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=ci(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=di(a+"{"+e+"}",f);ei(k,f);var m=k.parentNode;return function(){m.removeChild(k)}},gi=null,ci=function(a){if(gi)return gi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return gi=c}0==a.styleSheets.length&&
a.createStyleSheet();return gi=a.styleSheets[0]},di=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},ei=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var ni={},oi=void 0,pi=function(a){var b=ni[a];b||(b={id:a,v:[],W:0,Ia:null,za:void 0,Da:!1},ni[a]=b);oi=b},ri=function(a,b,c,d){var e=oi;if(!sg||!e)return!1;var f={id:e.id+":"+e.v.length,eb:b,U:[],Za:c,G:a,ua:0,sa:d||null,Na:0,V:!1};e.v.push(f);null===a?(f.V=!0,b(null)):qi(e);return!0},si=function(a){var b=fi(a,"visibility","hidden",!0);return function(){O(b)&&b.apply();b=null}},ti=function(a,b,c,d){var e=b;if(!Ta){var f=si(a.A);Ua.push(f);e=function(a,c){var d=b(a,c);f();return d}}return ri(a,e,
c,d)},qi=function(a){if(!a.Da){for(var b=a.W;b<a.v.length;b++){var c=a.v[b],d=b==a.W;if(!c.V&&!ui(d,c))break;c.V&&d&&a.W++}a.v.length>a.W?(a.Ia||(a.Ia=w.setTimeout(function(){a.Ia=null;qi(a)},80)),Ta||a.za||(a.za=function(){x(function(){qi(a)})},L(J,"DOMContentLoaded",a.za))):vi(a)}},vi=function(a){for(var b=0;b<a.v.length;b++){var c=a.v[b];if(c.G)for(var d=Da(c.G.A)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(wi(f,c.id),c.U.push(xi(f,c.id)))}}},ui=
function(a,b){var c=[];if(b.G){var d=yi(b.G,b.id),e=null;b.sa&&(e=yi(b.sa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!Ta&&(null===b.sa.o||b.Na+c.length<b.sa.o)))break;c.push({element:g,Hb:h})}}if(!Ta&&b.Za&&(!a||null==b.G.o||b.G.o!=b.ua+c.length))return!1;for(var k=0;k<c.length;k++){var m=c[k].element,l=c[k].Hb,p;b.ua++;wi(m,b.id);l&&(b.Na++,p=b.id+"-t",wi(l,p));var q=b.eb(m,l);O(q)&&b.U.push(q);b.U.push(xi(m,b.id));l&&p&&b.U.push(xi(l,p))}if(b.G.o&&
b.G.o==b.ua||Ta)b.V=!0;return!0},wi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},xi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},yi=function(a,b){for(var c=Da(a.A)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.D&&!zi(f))break;d.push(f)}}return d},zi=function(a){if(Ta)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var ja,Ai,Bi,ra=/(Firefox\D28\D)/g.test(Lf.userAgent),Di=function(a,b){return function(c){c=c||w.event;var d=va(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=wa(d,["a","area"]),e=!d||!d.href||Ci(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?ja:Bi;if(c.defaultPrevented||!1===c.returnValue||c.X&&c.X()){if(d){var g={simulateDefault:!1},h=ka(f,["wnc","nwnc"]);h&&la(a,d,g,f.wt,h)}}else{if(d){var g={},k,m=ka(f,["wnc",
"nwnc","nwc","wc"]);(k=la(a,d,g,f.wt,m))||(na(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&ra;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=ta(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},la=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||sa(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";
g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=Ei(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=Fi(b);g.eventTimeout=f;g.eventCallback=Gi(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ca(g)},Fi=
function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},qa=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},ta=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Lf.userAgent),e=qa(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=w.frames&&w.frames[f]||w[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+H().getTime(),b.targetWindow=w.open("",b.targetWindowName));break;default:d&&!w.frames[e]?(b.simulateDefault=!1,c=!0):(w.frames[e]||(b.targetWindowName=e),b.targetWindow=w.frames[e]||w.open("",e))}return c},Ei=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||H().getTime(),500>H().getTime()-c&&w.setTimeout(Ei(a,b,c),25)))}},Gi=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);J.gtmSubmitFormNow=!0;pa(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||H().getTime(),500>H().getTime()-c&&w.setTimeout(Gi(a,b,c),25)}},ka=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Hi=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},na=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<Ii.length;c++)if(a.passingRules[c]){var d=Ji[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Ii[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},Aa=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(J.gtmHasClickListenerTag)return;J.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=va(a);b&&la("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Ai&&(Ai=Uf(J.location));Hi(Bi,b||!1,c||!1,d,e);if(J.gtmHasLinkClickListenerTag)return;
J.gtmHasLinkClickListenerTag=!0;f="click";g=Di(a,b||!1);break;case "FORM_SUBMIT":Hi(ja,b||!1,c||!1,d,e);if(J.gtmHasFormSubmitListenerTag)return;J.gtmHasFormSubmitListenerTag=!0;f="submit";g=Di(a,b||!1);break;default:return}L(J,f,g,h)},Ci=function(a){if(!Ai)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ba(a);return Ai==Uf(c)},pa=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
J.gtmFormElementSubmitter||(J.gtmFormElementSubmitter=J.createElement("form"));return J.gtmFormElementSubmitter.submit.call?J.gtmFormElementSubmitter.submit:a.submit};var Pa=function(a,b){var c=b||cb,d=c.onerror,e=!1;vh&&!Dh("535.3")&&(e=!e);c.onerror=function(b,c,h,k,m){d&&d(b,c,h,k,m);a({message:b,fileName:c,Sa:h,Xb:k,error:m});return e}};var Hj=33,Ij=[],Jj=[],Kj=[],Lj=new tf,Mj=[],Z=[],Ii=[],Ji=[],Nj=function(){this.L=[]};Nj.prototype.set=function(a,b){this.L.push([a,b]);return this};Nj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.L.length;d++){var e=Oj(this.L[d][0],a,b),f=Oj(this.L[d][1],a,b);c[e]=f}return c};var Pj=function(a){this.index=a};Pj.prototype.resolve=function(a,b){var c=Kj[this.index];if(c&&!b(c)){var d=c[id];if(a){if(a.get(d))return;a.set(d,!0)}c=Oj(c,a,b);a&&a.set(d,!1);return Af(c)}};
var _M=function(a){return new Pj(a)},Qj=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Oj(Ij[a[f]],b,c);g===La&&(e=!0);d.push(g)}return e?new ch(d):d.join("")}},_T=function(a){return new Qj(arguments)},Rj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Oj(a[0],c,d);if(a[0]instanceof Pj&&b(8)&&b(16)){if(e===La)return e;var f=Ma();Lj.set(f,e);return'google_tag_manager["GTM-PN2MP4"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new Rj(arguments)},Sj=function(a,b){this.w=a;this.ra=b},_R=function(a,b){return new Sj(a,b)},Oj=function(a,b,c){var d=a;if(a instanceof Pj||a instanceof Nj||a instanceof Qj||a instanceof Rj)return a.resolve(b,c);if(!(a instanceof Sj))if(xa(a))for(var d=
[],e=0;e<a.length;e++)d[e]=Oj(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Oj(a[f],b,c))}return d},Tj=function(a,b){var c=b[a],d=c;if(c instanceof Pj||c instanceof Rj||c instanceof Qj||c instanceof Sj)d=c;else if(xa(c))for(var d=[],e=0;e<c.length;e++)d[e]=Tj(c[e],b);else if("object"==typeof c){var d=new Nj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Tj(c[f],b))}return d},Vj=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");
0==a&&(e[1]=Ij[e[1]]);if(1==a)for(var f=Uj(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Jj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Uj(e[g]);3==a&&(c[d]=Ij[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Ij[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Uj=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Hj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:
62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Wj=function(a,b,c){a.push.apply(a,Vj(b,c))};
var hg=function(){},ek=function(a){},kg=function(){},fk=function(a){},gk=function(a,b){},hk=function(a,b){},ig=function(a){};var ik,jk;var tk=function(a){return function(){}},uk=function(a){return function(){}};var vk=function(a){var b=this;this.g=a;this.complete=this.Wa=!1;this.qa=[];this.la=[];this.S=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||Ef(b.qa);If(b,1);if(kb[a])for(var e=0;e<kb[a].length;e++)kb[a].shift().S()};this.R=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||
Ef(b.la);If(b,2);if(kb[a])for(var e=0;e<kb[a].length;e++)kb[a].shift().R()};this.B=of},wk=function(a,b){a.qa.push(b)},xk=function(a,b){a.la.push(b)},yk=function(a){this.M=[];this.Ga=[];this.Pa={};this.ya=[];this.Y=0;this.Va={};this.Xa={};this.Ha={};this.event=a};yk.prototype.addListener=function(a){this.ya.push(a)};
var zk=function(a,b,c,d,e,f){if(!c.complete){a.M[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=xa(d)?d.slice():["or",d];e=xa(e)?e.slice():[e];f=xa(f)?f.slice():[f];a.Pa[b]=d;a.Va[b]=0<e.length;a.Xa[b]=0<f.length;a.Y++;var g=function(){0<a.Y&&a.Y--;0<a.Y||Ef(a.ya)};wk(c,g);xk(c,g)}},Ak=function(a,b,c){a.M[b]&&(wk(a.M[b],function(){c(b,!0)}),xk(a.M[b],function(){c(b,!1)}))},Bk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof Sj&&a[g].w===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Fk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Ck(h,b,a);if(f=g){var k=Dk(b,!0);0<k.length&&e(k[0].w);c.push(f);var l=Dk(b,!1);0<l.length&&e(l[0].w)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Dk(g.g,!0);if(0<h.length){var k=c[f-1],m=Ek(g);wk(k,m);0==h[0].ra&&xk(k,m)}var l=Dk(g.g,!1);0<l.length&&(m=Ek(c[f+1]),wk(g,m),0==l[0].ra&&xk(g,m))}a.Ga.push(c)}},Dk=function(a,b){var c=b?re:Ie,d=Z[a],e=void 0===d[c]?[]:d[c];return xa(e)?e:[e]},Ek=function(a){return function(){a.B()}},Hk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Dk(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=Dk(a,!1);0<c.length&&f(c[0].w)};
f(d.g);b[d.g]=e}Gk(a,b);return b},Gk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<rf(b[e],d)){delete b[d];break}}};var Jk=function(a,b){return function(){a[$c]=b.S;a[ad]=b.R;var c=b.g,d=b.s&&b.s.Ha[c],e=jb[c]&&jb[c].state,f=d?void 0!==d:b.Wa||b.Yb,g=jb[c]&&jb[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){If(b,0);var m=b.s?b.s.event:void 0;a=Ik(a,m?m.c:rg());if(m){var l=a;gk(m,c)}Af(a,b.S,b.R)}else h&&0==e||k&&0==d?kb[c].push(b):h&&1==e||k&&1==d?b.S():b.R()}},Ik=function(a,b){a=Oj(a,new tf,b);return a},Ck=function(a,b,c){var d=new vk(b);d.s=c;wk(d,tk(a));xk(d,uk(a));d.B=Jk(a,d);return d};var Mk=!1,Nk=!1;var Qk=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Mj[b]&&Oj(Mj[b],new tf,c),e=d;if(d)if(d[wb]&&xa(d[S]))for(var f=d[S],e=!1,g=0;!e&&g<f.length;g++)d[S]=f[g],e=Af(d);else e=Af(d);a[b]=[e,d]}return a[b]}},dk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.P(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.P(e[d],a.c)[0])return!1;return!0},Rk=!1,cg=function(a,b,c,d){switch(b){case "gtm.js":if(Rk)return!1;Rk=!0;break;case "gtm.sync":if(P("gtm.snippet")!=hb)return!1}P("tagTypeBlacklist");
for(var e={id:a,name:b,ha:c||of,fa:Uj(),pa:Uj(),P:Qk(),c:rg()},f=[],g=0;g<Ii.length;g++)if(dk(e,Ii[g])){f[g]=!0;for(var h=e,k=Ii[g],m=k[1],l=0;l<m.length;l++)h.fa[m[l]]=!0;for(var p=k[3],l=0;l<p.length;l++)h.pa[p[l]]=!0}else f[g]=!1;gk(e);var v=[];for(var y=0;y<Hj;y++)if(e.fa[y]&&!e.pa[y])if(e.c(Z[y])){}else{v[y]=Z[y];}e.T=v;for(var t=new yk(e),z=0;z<Hj;z++)if(e.fa[z]&&!e.pa[z])if(e.c(Z[z])){}else{var E=e.T[z],D=Ck(E,z,t);zk(t,z,D,E[wc],E[re],E[Ie]);if(E[lb])break}t.addListener(e.ha);for(var C=[],
A=0;A<t.M.length;A++){var M=t.M[A];if(M){var B=t.Pa[A],F=t.Va[A],N=t.Xa[A];if(0!=B.length||F||N){if(0<B.length)for(var T=Bk(B,M.B),R=0;R<B.length;R++)B[R]instanceof Sj&&B[R].w!=A&&Ak(t,B[R].w,T);(F||N)&&Fk(t,A)}else C.push(A)}}for(A=0;A<C.length;A++)t.M[C[A]].B();for(A=0;A<t.Ga.length;A++){for(var za=t.Ga[A],ha=void 0,V=za,ma=[],tb=0;tb<V.length;tb++){var bb=V[tb],Sb=bb.g,Hf=jb[Sb],ud=Hf.firingOption;0!=ud&&(1==ud&&void 0!==bb.s.Ha[Sb]||2==ud&&void 0!==Hf.state)&&ma.push(bb)}var vd=Hk(ma);for(ha in vd)if(vd.hasOwnProperty(ha)){for(var uf=
void 0,jj=void 0,od=vd[ha],el=od[0],lj=od[od.length-1],mj,Ka=0;Ka<V.length;Ka++){var pd=V[Ka];!uf&&pd.g==el&&0<Ka&&(uf=V[Ka-1]);pd.g==lj&&Ka<V.length-1&&(jj=V[Ka+1]);if(-1<rf(od,pd.g))if(mj=V.splice(Ka,1)[0],pd.g==lj)break;else Ka--}if(mj){var nj=Number(ha),oa=uf,vf=jj;if(oa){var fl=oa.qa[0],gl=oa.la[0],oj=oa;oj.qa=[];oj.la=[];wk(oa,fl);xk(oa,gl)}if(oa&&vf){var wf=Ek(vf);wk(oa,wf);var xf=Dk(oa.g,!1);0<xf.length&&xf[0].w!=nj&&0==xf[0].ra&&xk(oa,wf);var yf=Dk(vf.g,!0);0<yf.length&&yf[0].w!=nj&&0==yf[0].ra&&
xk(oa,wf)}}}0<za.length&&za[0].B()}0<t.Y||Ef(t.ya);d&&O(d)&&d({passingRules:f,resolvedTags:e.T});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var rj in e.T)if(e.T.hasOwnProperty(rj)){var sj=e.T[rj],zf;if(!(zf=void 0==sj[id])){var tj=sj[id];zf=!("function"!=typeof String.prototype.startsWith?0===tj.indexOf("_implicit"):tj.startsWith("_implicit"))}if(zf)return!0}return!1};var Sk={macro:function(a){if(Lj.contains(a))return Lj.get(a)}};Sk.dataLayer=Yf;Sk.onHtmlSuccess=fh(!0);Sk.onHtmlFailure=fh(!1);Sk.callback=function(a){$a.hasOwnProperty(a)&&O($a[a])&&$a[a]();delete $a[a]};Sk.jb=function(){var a=w.google_tag_manager;a||(a=w.google_tag_manager={});a["GTM-PN2MP4"]||(a["GTM-PN2MP4"]=Sk);Ra=a};(function(){var a=function(a){var b=Q("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Bi=a("linkClickMap");ja=a("formSubmitMap")})();
Ij.push.apply(Ij,function(){for(var a=[_f,'referrer',_u,'url path','path','url hostname','host','url',_v,'element id','gtm.elementId','element classes','gtm.elementClasses','element','gtm.element',_e,'event','element target','gtm.elementTarget',_et,'element text','element url','gtm.elementUrl','history new url fragment','gtm.newUrlFragment','history old url fragment','gtm.oldUrlFragment','history new state','gtm.newHistoryState','history old state','gtm.oldHistoryState','history change source','gtm.historyChangeSource'],b=[],c=0;c<a.length;c++)b[c]=Tj(c,a);return b}());Wj(Jj,0,"1:0,2:1,1:2,2:3,0:4,2:5,0:6,2:7,1:8,2:9,3:10,2:11,3:12,2:13,3:14,1:15,2:16,2:17,3:18,1:19,2:20,2:21,3:22,2:23,3:24,2:25,3:26,2:27,3:28,2:29,3:30,2:31,3:32");Wj(Kj,1,"D,c,kB,EC,Ac,AkB,AEG,AAY,AEgB,AAAG,AEAY,AEAgB,AEAAG,AEAAY,AEAAgB,AEAAAG");Wj(Mj,1,"");Wj(Z,1,"");Wj(Ii,2,"");Wj(Ji,4,"");for(var Tk=0;Tk<Z.length;Tk++){var Uk=Z[Tk],Vk=1;Uk[Pd]?Vk=2:Uk[$e]&&(Vk=0);jb[Tk]={firingOption:Vk,state:void 0};kb[Tk]=[]}Sk.jb();
(function(a){})("async");
(function(){var a=Q("dataLayer",[]),b=Q("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||{};Ua.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Rf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(dg.push.apply(dg,b);300<this.length;)this.shift();return lg()};dg.push.apply(dg,a.slice(0));x(mg)})();var cl=w;
if("interactive"==J.readyState&&!J.createEventObject||"complete"==J.readyState)Nf();else{L(J,"DOMContentLoaded",Nf);L(J,"readystatechange",Nf);if(J.createEventObject&&J.documentElement.doScroll){var dl=!0;try{dl=!cl.frameElement}catch(a){}dl&&Pf()}L(cl,"load",Nf)}"complete"===J.readyState?Sf():L(w,"load",Sf);
(function(a){})("async");(function(){})();var _vs="res_ts:1412089070352000,srv_cl:143751674,ds:live,cv:1";
})()
