(function(){function k(f){window.__ATA_DEBUG&&"undefined"!==typeof console&&console.info&&console.info(new Date," -> ",f.replace("http","htt_p"))}function m(f){var d=this,b="section_id tz fl click3rd slot_id ref pos".split(" ");this.j={};this.o=!1;this.b=f;this.f=new n(this);this.I=function(d){return this.j[d]};this.K=function(){if(!d.o){d.o=!0;var a=document.createElement("iframe");a.style.cssText="position:absolute;left:-1000px;top:-1000px;border:0 solid;width:0;height:0;";a.width=a.height=0;a.name=
s;a.src=p+"#"+location.protocol+"//"+location.host;document.body.appendChild(a);d.L=d.b.onPassbackReceived=function(c){var a,b=c.id,b=b&&b.replace("fif_slot_"+q+"_","");if((a=d.I(b))&&a.c&&a.c.length){try{c.id=c.name="dead_"+c.name;c.style.cssText="border:none;position:absolute;width:0;height:0;left:-10000px;top:-10000px;";var g=c.contentWindow;g.name=c.id;g&&g.document&&"complete"===g.document.readyState&&c.parentNode&&c.parentNode.removeChild(c)}catch(f){}c=a.c.shift();a.h&&((new Image).src=a.h);
c.noad_url&&((new Image).src=c.noad_url);a={a:b,i:a.i,data:c.data,type:a.type,width:a.width,height:a.height,c:a.c,h:c.passback_url};d.j[a.a]=a;d.f.p(d.e(),a)}};d.f.r(function(c){if(c.origin===h&&c.source){c=c.source;for(var a=c.parent;a!==window&&a!==window.top;)c=a,a=a.parent;if(c&&a===window)try{d.L(c.frameElement)}catch(b){k("No access to iframe from postMessage "+b)}}})}};this.v=this.b.displayAd=function(a,c){k('<span class="blue">displayAd is called for ID:</span> '+a);var b=d.b.ids;b&&b[a]&&
delete b[a];var e,g,f,h;e=document.getElementById(a);f=parseInt(e.style.width,10);h=parseInt(e.style.height,10);g=e.getAttribute("data-type")||"adj";b=t;e={a:a,i:e.getAttribute("data-section"),w:e.getAttribute("data-forcedurl"),g:c,type:g,width:f,height:h};b=e.w||d.A(b,e);k("Ad server full URL: "+b);d.P(e,b)};this.s=function(a,c){var d,b=this.Q,g=this;d=(u+"_"+a.a).replace(/[^a-zA-Z0-9_\$]/g,"_");window[d]=function(c){try{delete window[d]}catch(f){window[d]=void 0}var h=document.getElementById("slots_script_"+
a.a);h&&h.parentNode.removeChild(h);b.call(g,c,a)};return c+((-1<c.indexOf("?")?"&":"?")+"callbackPubmine="+d)};this.P=function(a,c){var b,e,g;c=d.s(a,c);b="slots_script_"+a.a;d.e()?(b='<script type="text/javascript" src="{{url}}" id="{{id}}">\x3c/script>'.replace("{{url}}",c).replace("{{id}}",b),document.write(b)):(e=document.createElement("script"),e.async=!0,e.type="text/javascript",e.src=c,e.id=b,g=document.getElementsByTagName("script")[0],d.m()?setTimeout(function(){g.parentNode.insertBefore(e,
g)},0):g.parentNode.insertBefore(e,g))};this.Q=function(a,c){var b=c.g;a&&a.data?(c.data=a.data,c.h=a.passback_url,c.c=a.subs,d.j[c.a]=c,c.c&&c.c.length&&d.K(),b&&"function"===typeof b.renderStartCallback&&b.renderStartCallback(c),d.f.p(d.e(),c)):b&&"function"===typeof b.noContentCallback&&b.noContentCallback(c,a)};this.t=function(){var a,c,d;c=this.b.ids;if(null!==c&&"object"===typeof c){try{d=this.b.customParams||{}}catch(b){return}for(a in c)c.hasOwnProperty(a)&&this.v(a,d)}};this.A=function(a,
c){c=c||{};var b,e,g,f;b="https:"===document.location.protocol;g=[];f=this.G();e=a.replace(/^http:|^https:|\?$/im,"");e=(b?"https:":"http:")+e+c.type+"/";b="";top!==self&&(b=encodeURIComponent(document.referrer));b=["tz="+(new Date).getTimezoneOffset(),"fl="+d.C(),"ref="+b||"","pos="+d.J(c.a)||"","sfv=2"];e+=c.i+"/"+c.width+"/"+c.height+"/";g=g.concat(b);d.k(d.b.g,g);d.k(c.g,g);"undefined"!==typeof d.b.u&&g.push("click3rd="+encodeURIComponent(d.b.u));!1!==f&&g.push("lang="+encodeURIComponent(f));
return e+"?"+g.join("&")+"&ord="+Math.floor(1E13*Math.random())};this.k=function(a,c){var f,e;if("undefined"!==typeof a)a:for(f in a){e=0;for(var g=b.length;e<g;e++)if(b[e]+""===f+"")continue a;if(a.hasOwnProperty(f)){e=a[f];if(d.isArray(e)){for(g=0;g<e.length;g++)e[g]=encodeURIComponent(e[g]);c.push(f+"="+e.join("|"));continue a}c.push(f+"="+encodeURIComponent(e))}}};this.e=function(){return!0===d.b.isSync};this.t()}function n(f){var d=this;f instanceof m&&(this.q=f);this.p=function(b,a){k('<span class="green">Slot rendering method is invoked for ID:: '+
a.a+" with "+a.type+" content</span>");b?this.O(a):this.N(a)};this.O=function(b){"adj"===b.type?document.write('<script type="text/javascript">'+b.data+"\x3c/script>"):document.write(b.data)};this.N=function(b){var a,c,f;if(a=document.getElementById(b.a)){c=d.M(b);c.src="javascript:\"<html><body style='background:transparent;margin:0%;'></body></html>\"";a.appendChild(c);switch(b.type){case "adj":f='<html><body style=\'background:transparent;margin:0%;\'><script type="text/javascript">var inDapIF=true;\x3c/script><script type="text/javascript">'+
b.data+"\x3c/script></body></html>";break;case "adi":f=b.data}b=d.l();0!==d.F()||b?(c=window.frames[c.name],c.contents=f,c.location.replace(d.B())):(c=c.contentWindow?c.contentWindow.document:c.contentDocument,-1!==navigator.userAgent.indexOf("Firefox")&&c.open("text/html","replace"),c.write(f),d.m()||c.close())}else k("Not ready to render: "+b.a)};this.M=function(b){var a=document.createElement("iframe"),c="border:none;",f=d.D(b.a);d.n(b.width)&&(c+="width:"+b.width+"px;",a.width=b.width);d.n(b.height)&&
(c+="height:"+b.height+"px;",a.height=b.height);a.setAttribute("style",c);a.setAttribute("frameBorder","0");a.setAttribute("scrolling","no");a.name=f;a.id=f;return a};this.B=function(){return d.l()&&!d.q.e()?"javascript:document.write(window.contents);":"javascript:window.contents"};this.D=function(b){return"fif_slot_"+q+"_"+b};this.r=function(b){var a=window;a.addEventListener?a.addEventListener("message",b,void 0):a.attachEvent("onmessage",function(){return b.call(a,window.event)})}}function r(){var f=
this;this.C=function(){var d=0,b;if(f.d(navigator.plugins)&&"object"===typeof navigator.plugins["Shockwave Flash"])!(b=navigator.plugins["Shockwave Flash"].description)||f.d(navigator.mimeTypes)&&navigator.mimeTypes["application/x-shockwave-flash"]&&!navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(b=b.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),d=parseInt(b.replace(/^(.*)\..*$/,"$1"),10));else if(f.d(window.ActiveXObject))try{var a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");a&&
(b=a.GetVariable("$version"))&&(b=b.split(" ")[1].split(","),d=parseInt(b[0],10))}catch(c){}return d};this.d=function(d){return"undefined"!==typeof d};this.n=function(d){return f.d(d)&&null!==d&&""!==d+""};this.F=function(){var d=navigator.userAgent,b=d.indexOf("MSIE ");return-1===b?0:parseFloat(d.substring(b+5,d.indexOf(";",b)))};this.l=function(){var d=navigator.userAgent;return null!==d.match(/\d\sNavigator\/\d/)||null!==d.match(/\d\sNetscape\/\d/)};this.m=function(){return-1!==navigator.userAgent.indexOf("Opera")};
this.isArray=function(d){return"[object Array]"===Object.prototype.toString.call(d)};this.H=function(){var d=0,b=0;"number"===typeof window.innerHeight?(d=window.innerHeight,b=window.innerWidth):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)&&(d=document.documentElement.clientHeight,b=document.documentElement.clientWidth);return{width:b,height:d}};this.J=function(d){d=document.getElementById(d);for(var b=f.H(),a=d?d.offsetTop:0;d&&null!==d.offsetParent&&
(d=d.offsetParent,a+=d.offsetTop,"BODY"!==d.tagName););(a||0===a)&&b.height?a>b.height?a="btf":a="atf":a="";return a};this.G=function(){for(var d=document.getElementsByTagName("meta"),b,a=!1,c=0;c<d.length;c++)if(b=!1,d[c]&&(b=d[c].getAttribute("http-equiv")||d[c].httpEquiv),b&&"content-language"===b.toLowerCase()){a=(a=d[c].getAttribute("content")||d[c].content)||!1;break}return a}}var t="//s.pubmine.com/",l=window.__ATA,q=l.slotPrefix,u="automattic_jsonp_handler",s=l.passbackReceiver,p=l.passbackSrc,
h=(p.match(/^(?:[a-z]+\:)?(?:\/\/)?[a-zA-Z0-9_\-\.]+/)||[""])[0];h.search(/https?\:\/\//)&&(h=location.protocol+h);m.prototype=new r;n.prototype=new r;new m(l)})();
