#!/bin/bash
# Push Coala fixes back to the repo if on gh-pages branch
FIX_BRANCH='$FIX_BRANCH'-'$TRAVIS_BUILD_NUMBER' # make a branch per fix
echo $FIX_BRANCH
if [ "$TRAVIS_BRANCH" = "gh-pages" ]; then
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "coala-autofix-bot"
    git checkout -B $FIX_BRANCH
    git add .
    git commit --message "Coala auto-patch for Travis CI Build:$TRAVIS_BUILD_NUMBER | Generated by Travis CI"
    git remote add origin-pages https://coala-autofix-bot:$COALA_FIXER@github.com/fossasia/gci16.fossasia.org.git
    git pull --rebase origin-pages $FIX_BRANCH
    git push --quiet --set-upstream origin-pages $FIX_BRANCH

    curl -X POST -H "Authorization: token $GITHUB_TOKEN" --data '{"title":"coala-fixes for build '$TRAVIS_BUILD_NUMBER'", "body":"Automated Coala fixes:'$TRAVIS_BUILD_NUMBER'", "head":"'$FIX_BRANCH'", "base":"gh-pages"}' https://api.github.com/repos/fossasia/gci16.fossasia.org/pulls;
else
    echo "Not committing a patch since we are not on the gh-pages branch"
fi
