// v:12.6.7
var skimlinks_domain = 'wordpress.redirectingat.com';
var skimlinks_legacy_support = true;
var skimlinks_cookie_sync_optout = true;
var skimlinks_audience_optout = false;
var skimlinks_first_party_na = false;
var skimwords_horizontal_distance = 80;
var skimwords_vertical_distance = 80;
var skimlinks_replace_timeout = 300;
var noskimproducts = true;
var skimlinks_legacy_click_handlers = false;
var skimlinks_affiliate_unknown_links = true;
var skimwords_instant = true;
if (typeof noskimwords === "undefined") {
var noskimwords = true;
}
var noskoupon = true;
var skimlinks_pub_id = '725X1342';

(function(h){var Gc,Hc,va,aa;aa=function(){var a,b,c,d,e,f,i,o,g,h,l,k,t,u,m,n,p,q;if(aa)return aa;d=function(a){return((null!=a?a[0]:void 0)||2)*{minutes:60,hours:3600,days:86400}[(null!=a?a[1]:void 0)||"days"]};n=[{label:"lotame",url:"//bcp.crwdcntrl.net/5/c=7507/pv=y?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dlotame%26skim_mapping%3Dtrue%26provider_id%3D%24%7Bprofile_id%7D",resyncAfter:[2,"days"],priority:1,active:!0},{label:"blue_kai",url:"https://stags.bluekai.com/site/27381?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dblue_kai%26skim_mapping%3Dtrue%26provider_id%3D%24_BK_UUID",
resyncAfter:[1,"days"],priority:2,active:!0},{label:"dfp",url:"//cm.g.doubleclick.net/pixel?google_nid=skimlinks_ddp&google_cm",resyncAfter:[1,"days"],priority:2,active:!0},{label:"mediamath",url:"//pixel.mathtag.com/sync/img?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dmediamath%26skim_mapping%3Dtrue%26provider_id%3D%5BMM_UUID%5D%26provider_dc%3D%5BMT_DC%5D",resyncAfter:[1,"days"],priority:2,active:!0},{label:"app_nexus",url:"https://secure.adnxs.com/getuid?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%24UID%26provider%3Dapp_nexus%26skim_mapping%3Dtrue",
resyncAfter:[1,"days"],priority:2,active:!0},{label:"eyeota",url:"//ps.eyeota.net/match?bid=dn9h51u&r=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Deyeota%26provider_id%3D%7BUUID_dn9h51u%7D%26skim_mapping%3Dtrue",resyncAfter:[1,"days"],priority:2,active:!0},{label:"magnetic",url:"//magnetic.t.domdex.com/sync/skimlinks",resyncAfter:[7,"days"],priority:2,active:!0},{label:"exelate",url:"//x.skimresources.com/?provider=exelate",resyncAfter:[1,"days"],priority:2,active:!0},{label:"exelate2",url:"//x.skimresources.com/?provider=exelate2",
resyncAfter:[1,"days"],priority:2,active:!0},{label:"krux",url:"//x.skimresources.com/?provider=krux",resyncAfter:[1,"days"],priority:2,active:!0},{label:"avocet",url:"https://ads.avocet.io/getuid?url=https%3A%2F%2Fx.skimresources.com%2F%3Fskim_mapping%3Dtrue%26provider%3Davocet%26provider_id%3D%7B%7BUUID%7D%7D",resyncAfter:[1,"days"],priority:2,active:!0},{label:"tapad",url:"//x.skimresources.com/?provider=tapad",resyncAfter:[3,"days"],priority:3,active:!0},{label:"skim",url:"//x.skimresources.com/?provider=skim",
resyncAfter:[5,"days"],priority:3,active:!0}];o={};b=function(a,b){var c,d,e,f;if(a.filter)return null!=(c=a.filter)?"function"===typeof c.call?c.call(a,b):void 0:void 0;d=[];for(c=e=0,f=a.length;0<=f?e<f:e>f;c=0<=f?++e:--e)b(a[c])&&d.push(a[c]);return d};h=function(a){o.syncCheck=a[0];o.getCookieSyncInfo=a[1];o.getServerTime=a[2];return o};t=function(a,b,c){return Boolean(a.timestamp+d(b.resyncAfter)<=c)};q=function(a){return o.getServerTime(function(b){var c;c=g(a,b);return setInterval(function(){if(c.length)return i(c.shift())},
200)})};m=function(a,b){var c;c=Math.max(1,Number(a.priority))-1;null==b[c]&&(b[c]=[]);return b[c].push(a)};p=function(a){var b,c,d,e;for(c=a.length;c;)d=Math.floor(Math.random()*c--),b=c,e=a[b],a[b]=a[d],a[d]=e;return a};g=function(a,c){var d,e,f,i,o;d=b(n,function(b){var d;return!b.active?!1:(d=a[b.label])?t(d,b,c):!0});e=[];f=b(d,function(a){return 1===a.priority});d=f.length?f:d;for(i=0,o=d.length;i<o;i++)f=d[i],m(f,e);f=[];for(i=0,o=e.length;i<o;i++)d=e[i],null!=d&&f.push.apply(f,p(d));return f};
l=function(a){return q(u(a))};u=function(a){var b,c,d,e,f;d={};if(!a)return d;f=a.split("|");for(a=0,e=f.length;a<e;a++)b=f[a],b=b.split(":"),c=b[0],d[c]={label:c,timestamp:parseInt(b[1])};return d};k=function(a){a.width=0;a.height=0;return a.style.display="none"};e=function(a,b){var c;null==b&&(b=j);c=b.createElement("img");c.src=a;c.width=1;c.height=1;return c};a=function(a,b){var c;null==b&&(b=j);null!=(c=b.getElementsByTagName("body")[0])&&c.appendChild(a);return a};c=null;f=function(){var b;
c=b=c||a(j.createElement("iframe"));k(b);return b.contentDocument||b.contentWindow.document};i=function(b){var c;c=f();return a(e(b.url,c),c)};return{init:function(){h(arguments);if(o.syncCheck())return o.getCookieSyncInfo(l)},__private__:{day:86400,isTimeToSync:t,configToSeconds:d,parseSyncCookie:u,getSuitableProviders:g,setProviders:function(a){return n=a}}}}();var Y,Ic,Jc,Kc,ba,Lc,Mc,Nc,Oc,Lb,l,s,Mb,wa,Nb,Ob,Pb,Na,Oa,Pc,fb,Qc,Rc,Qb,Rb,j,p,Pa,gb,Sb,hb,w,n,y,Tb,S,ca,xa,da,ib,ya,ea,za,Aa,Sc,Ub,q,
Ba,Qa,Vb,jb,fa,ga,Tc,Uc,g,Vc,Ca,Wc,Xc,kb,T,Yc,Zc,Ra,ha,Wb,$c,ad,bd,cd,I,dd,lb,ia,Xb,mb,ja,ka,la,Yb,nb,Sa,ed,fd,Ta,gd,hd,Da,id,Ua,Zb,ma,$b,jd,r,kd,ac,ld,ob,Va,md,Wa,nd,bc,Xa,pb,od,cc,qb,pd,dc,ec,qd,rb,fc,L,gc,hc,ic,rd,U,jc,kc,lc,sb,mc,nc,na,tb,oc,O,Ya,ub,J,pc,Z,Ea,vb,qc,Za,wb,xb,yb,zb,Ab,V,$a,Fa,Bb,E,Ga,A,B,oa,rc,K,sd,Cb,td,ab,ud,G,sc,tc,vd,Db,uc,vc,W,v,x,Eb,wc,xc,Ha,pa,M,N,bb,qa,Ia,ra,C,D,yc,H,wd,z,xd,P,zc,F={}.hasOwnProperty,sa=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&
this[b]===a)return b;return-1};da=ib=null;"undefined"!==typeof skimlinks_context_window&&null!==skimlinks_context_window&&(h=h[skimlinks_context_window]);j=h.document;ya=/http:/g;n=function(){return function(){var a;a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||0}}}(this)();fa=[];ga=
[];q={};Vb=(new Date).getTime();Ba=[];Sc=["buy.itunes.apple.com","itunes.apple.com","itunes.com"];jb={"t.umblr.com":{name:"z"}};ea=S=null;Qa=xa=!1;za=[];ca=[];Aa=[];y={domains:[]};w={};Tb=null;Ub=[];V=B=null;O="";Ga=E=$a=Ya=null;na=[];Z=[];J=Bb=sb=tb=Za=null;Ea=!1;qc="beginning";vb=[];A=oa=!1;mc="skimlinksApplyHandlers";Fa=!1;wb=300;nc=oc=zb=yb=xb=Ab=pc=kc=lc=!1;tc=[];ra=qa=Ia=bb=C=null;H=D=v="";N=x=0;Ha=xc=pa=vc=yc=!1;W=[];M=!1;uc=!0;wc=!1;Eb=[];z=h.location;P="";Y=!1;ab=null;Xa={};Db=[];bc=!1;gb=
[];Gc=["noskim","norewrite"];Hc="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com,paid.outbrain.com,trc.taboola.com,traffic.outbrain.com,zergnet.com,*.criteo.com".split(",");ub=function(){return!0};va=[];Ca=function(a){var b;b=j.createElement("a");b.href=a;return K(b.hostname)};pd=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};Tc=function(){var a,b;a="";for(b=0;8>b;++b)a+=pd();
return a};g=function(){return function(a,b){return null!=h[a]?h[a]:null!=window[a]?window[a]:b}}(this);Lc=function(){var a;H=Tc();ib=null!=(a=j.getElementsByTagName("html"))?a[0]:void 0;za=g("skimlinks_included_classes",[]);ca=g("skimlinks_excluded_classes",[]);Aa=g("skimlinks_included_ids",[]);da=g("force_location")?Ca(g("force_location")):z.hostname;B=g("skimlinks_tracking",!1);B=g("affiliate_tracking",B);V=g("skimlinks_site")||g("skimlinks_sitename")||!1;O=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):
"";Ya=g("skimlinks_google",!1);$a=null!=Ya?Ya:"skimout";E=g("skimlinks_target",!1);Ga=g("sl_test",!1);g("skimlinks_cookie_sync",[]);na=g("skimlinks_exclude",[]);Z=g("skimlinks_include",[]);Za=g("skimlinks_noright",!1);tb=g("skimlinks_exrel",!1);sb=g("skimlinks_byrel",!1);kc=g("skimlinks_add_nofollow",!1);Bb=g("skimlinks_blocked_tag",!1);oa=g("skimlinks_revenue_forecast",!1);Fa=g("skimlinks_strip_attribute",!1);g("skimlinks_ad_images",!1);"number"===typeof g("skimlinks_replace_timeout")&&(wb=g("skimlinks_replace_timeout"));
"boolean"===typeof g("skimlinks_before_click_handler")&&(lc=g("skimlinks_before_click_handler"));J=0;A=ad();Ab=g("skimlinks_retargetting_trigger",!1);xb=g("skimlinks_retargetting_adv_id",!1);yb=g("skimlinks_retargetting_pix_id",!1);pc=g("skimlinks_ignore_hidden_links",!1);zb=!1;oc=g("skimlinks_first_party_na",!1);"undefined"!==typeof skimlinks_cookie_sync_optout&&null!==skimlinks_cookie_sync_optout&&(nc=skimlinks_cookie_sync_optout);g("skimwords_live_scraping",!1);bc=g("skimlinks_url_extraction_rules",
!1);gb=g("skimlinks_extra_redir_params",[]).join("&");h.skimlinks_revenue_forecast=window.skimlinks_revenue_forecast=!1;C=g("skimlinks_pub_id","");Ub=g("skimlinks_link_impression_exclude_selector",[]).join(", ");if(g("skimlinks_legacy_support"))h.skimlinks=window.skimlinks=function(){return!0},g("mugicPopWin")&&(h._mugicPopWin=window._mugicPopWin=h.mugicPopWin),h.mugicPopWin=window.mugicPopWin=function(){return!0},h.mugicRight=window.mugicRight=function(){return!0},h.mugicRightClick=window.mugicRightClick=
function(){return!0};x=g("skimlinks_dnt",0);N=g("skimlinks_nocookie",!1);N=g("skimlinks_nocookie",!1);bb=g("noimpressions",!1);qa=g("noskimlinks",!1)||g("noskim",!1)||!1;M=g("skimlinks_legacy_click_handlers",!1);uc=g("skimlinks_affiliate_unknown_links",!0);qa&&($.skimlinks=!1);(Ia=g("noskimwords",!1)||g("noskim",!1)||!1)&&($.skimwords=!1);ra=g("nounlinked",!1)||g("noskim",!1)||!1;tc=g("unlinked_excludes",[]);ra&&($.unlinked=!1);yc=g("skim_toolbar",!1);vc=g("skimlinks_ajax_rerun",!1);g("skimlinks_editor",
!1);xc=g("skimlinks_ipc",!1);Ha=g("skimlinks_ipc_diy",!1);wc=g("skimlinks_dwell_tracking",!1);Eb=g("skimlinks_dwell_allowed_urls",[]);g("_merchantSettings")&&"undefined"===typeof replace_url_field?(pa=!0,mc="skimlinksApplyHandlersAlt"):pa=!1;Ea=g("skimlinks_ipc_decoration",!1);qc=g("skimlinks_ipc_position","beginning");vb=g("skimlinks_ipc_domain_whitelist",[]);if(h.document&&h.document.referrer)P=h.document.referrer;id(da)&&(Ia=qa=!0);B&&!/^[a-z0-9_\\|]+$/i.test(B)&&(B=!1);if("undefined"!==typeof m&&
null!==m)m.pag=k.pag=g("force_location",z.href),m.pub=k.pub=C,m.uc=k.uc=B;"undefined"!==typeof assign_skimwords_globals&&null!==assign_skimwords_globals&&assign_skimwords_globals();ca.push("noskimlinks");ca.push("noskim");ab=j.createTextNode("").nodeName;return!0};xd=function(){return!nc};wd=function(a,b){return a.hasOwnProperty(b)};ad=function(){var a;return"function"===typeof(a=new Date).getTimezoneOffset?a.getTimezoneOffset():void 0};id=function(a){var b,c,d,e;if(c=g("noskim_domains",!1))for(d=
0,e=c.length;d<e;d++)if(b=c[d],-1!==a.toLowerCase().indexOf(b.toLowerCase()))return!0;return!1};K=function(){return function(){var a;a=/^www\./i;return function(b){return b.replace(a,"")}}}(this)();s=function(){return function(){return j.addEventListener?function(a,b,c,d){null==d&&(d=!1);if(a&&(a.nodeName||a===h))return a.addEventListener(b,c,d)}:function(a,b,c){if(a&&(a.nodeName||a===h))return a.attachEvent("on"+b,function(){return 7>n.version&&!h.event?(setTimeout(function(){return c.call(a,h.event)},
100),!0):c.call(a,h.event)})}}}(this)();(function(){return function(){return j.createElement("div").getElementsByClassName?function(a,b){return I(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=Pb(b);return Sb(a,c)}}})(this)();p=function(){return function(){var a,b;b=[function(){var b,d,e,f;e=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];f=[];for(b=0,d=e.length;b<d;b++)a=e[b],f.push([RegExp(a[0],"g"),a[1]]);return f}()];return function(c){var d,
e,c=encodeURIComponent(c);for(d=0,e=b.length;d<e;d++)a=b[d],c=c.replace(a[0],a[1]);return c}}}(this)();Sa=function(){return function(){var a;a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||!da||-1===c.indexOf(da))&&(!da||-1===da.indexOf("."+c))}}}(this)();l=function(a,b,c){var d;3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{return d=a[b],null==d&&(d=a.getAttribute(b)),d}catch(e){return null}};Oa=function(a,b,c){arguments[1]="data-"+b;
return l.apply(this,arguments)};td=function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)"undefined"!==typeof a.innerText?a.innerText=b:a.textContent=b,c=b;return c};lb=function(a){return(""+a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")};G=function(){return function(){var a,b;if(String.prototype.trim)return function(a){return null===a?"":String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,
b=/[\s\xA0]+$/);return function(c){return null===c?"":c.toString().replace(a,"").replace(b,"")}}}(this)();Ic=function(a,b){return!I(a,b)?(a.className+=" "+b,!0):!1};ld=function(a){var b,c,d,e,f;if("object"===typeof a||a instanceof Array){e="";d=0;c=a instanceof Array;for(f in a)F.call(a,f)&&(b=a[f],0<d&&(e+=","),c?e+=r(b):(b=r(b),e+='"'+f+'":'+b),d++);return c?"["+e+"]":"{"+e+"}"}return"string"===typeof a?(b=a.replace(/"/g,'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};r=function(){return function(){var a;
return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?(a=JSON.stringify,function(b){return a(b)}):ld}}(this)();Pa=function(){return function(){var a,b;a=/[-[\]{}()*+?.,\\^$|#\s]/g;b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"s+")}}}(this)();qb={topics:{},on:function(a,b){var c;if(null==(c=this.topics)[a])c[a]=[];return this.topics[a].push(b)},off:function(a,b){var c;c=0<=sa.call(this.topics[a],b);if(-1<c)return this.topics[a].splice(c,
1)},once:function(a,b){var c;c=function(a){return function(){c.called||b.apply(a,arguments);return c.called=!0}}(this);c.called=!1;return this.on(a,c)},publish:function(a,b){var c,d,e,f,i,o;c={topic:a,extra:b};if(this.topics[a]){i=this.topics[a];o=[];for(e=0,f=i.length;e<f;e++)d=i[e],o.push("function"===typeof d?d(c):void 0);return o}}};Pb=function(a){a=Pa(a);return RegExp("\\b"+a+"\\b","i")};I=function(a,b){return a.className?Pb(b).test(a.className):!1};Sb=function(a,b){var c,d,e,f,i;d=[];a.className&&
b.test(a.className)&&d.push(a);i=a.childNodes;for(e=0,f=i.length;e<f;e++)c=i[e],d=d.concat(Sb(c,b));return d};Ua=function(a){for(var b,c,d,e;a&&a!==ib;){c=a.id;for(d=0,e=za.length;d<e;d++)if(b=za[d],I(a,b))return!1;for(d=0,e=Aa.length;d<e;d++)if(b=Aa[d],c===b)return!1;for(c=0,d=ca.length;c<d;c++)if(b=ca[c],I(a,b))return!0;a=a.parentNode}return za.length||Aa.length?!0:!1};la=function(a,b,c){null==c&&(c=!1);for(b=RegExp("\\b(?:(?:"+Pa(b)+")|(?:noskim))\\b","i");null!=a&&a!==ib;){if(a.className&&b.test(a.className))return!0;
a=c?null:a.parentNode}return!1};Nb=function(a,b){var c,d,e,f,i,o,h;C||(C=g("skimlinks_pub_id",""));o=P?"&pref="+p(P):"";c=!1;0<b.indexOf("#slm-")&&(d=b.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1])===10*d[1]&&(b=d[0],c=d[1]));e=l(a,"data-skimlinks-editor")&&1===parseInt(l(a,"data-skimlinks-editor"))?1:0;O||(O=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):Na());I(a,"skimwords-link")?(h=l(a,"data-skimwords-word"),d=l(a,"data-skim-creative"),f=l(a,"data-skim-product"),i=g("skimlinks_domain")?
"http://"+g("skimlinks_domain"):Na(),"undefined"!==typeof settings&&null!==settings&&(i=settings.sw_domain||i),b=""+i+"/?id="+C+""+(B?"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=2")+"&url="+p(b)+"&xguid="+v+"&xuuid="+H+"&xsessid="+D+"&isjs=1&xword="+(h?h:"")+"&xcreo="+(d?d:"")+"&xpid="+(f?f:"")+"&xed="+e+"&sref="+p(z)+""+o+""+(x?"&dnt="+x:"")+""+(N?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:"")):I(a,"skimlinks-inline")?(d=l(a,"data-skim-creative"),b=""+O+"/?id="+C+""+(V?"&site="+V:
"")+""+(Ga?"&test="+Ga:"")+""+(B?"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=8")+"&isjs=1&url="+p(b)+"&xguid="+v+"&xuuid="+H+"&xsessid="+D+"&xcreo="+(a&&null!=d?d:0)+"&xed="+e+"&sref="+p(z)+"&pref="+p(P)+""+(x?"&dnt="+x:"")+""+(N?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:"")):la(a,"noskimlinks")||(d=l(a,"data-skim-creative"),b=""+O+"/?id="+C+""+(V?"&site="+V:"")+""+(Ga?"&test="+Ga:"")+""+(B?"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=1")+"&isjs=1&url="+p(b)+"&xguid="+v+"&xuuid="+H+"&xsessid="+
D+"&xcreo="+(a&&null!=d?d:0)+"&xed="+e+"&sref="+p(z)+""+o+""+(x?"&dnt="+x:"")+""+(N?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:""));0<gb.length&&(b+="&"+gb);Y&&!la(a,"noskimlinks")&&(b+="&abp=1");return b};kb=function(a){var b,c;b=a.target||a.srcElement;if(M&&b&&!b.href&&a.currentTarget)b=a.currentTarget;a=null!=b?null!=(c=b.nodeName)?"function"===typeof c.toUpperCase?c.toUpperCase():void 0:void 0:void 0;"A"!==a&&"AREA"!==a&&(b=Ra(b));return b};L=function(a){var b;b=kb(a);if(!b)return!0;
ec(b);if(g("vglnk")&&I(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=h.event,a.cancelBubble=!0);return!0};Ra=function(a){for(;a.parentNode;)if(a=a.parentNode,"A"===(null!=a?a.nodeName.toUpperCase():void 0)||"AREA"===(null!=a?a.nodeName.toUpperCase():void 0))return a;return null};sd=function(a){return a=v?a.replace(/([&\?]{1})xguid=([a-fA-F0-9]{32})/,"$1xguid="+v):a.replace(/([&\?]{1}xguid=[a-fA-F0-9]{32})/,"")};Ob=function(a,b){var c,d;d=a();if(null!=d)return function(a){return a(d)};
c=null;qb.once(b,function(){return"function"===typeof c?c(a()):void 0});return function(a){return c=a}};Wc=function(){var a;return null!=(a=va[0])?a.guid:void 0};Vc=Ob(function(){var a;return null!=(a=va[0])?a.csp:void 0},"beacon");bd=Ob(function(){var a;return null!=(a=va[0])?a.ts:void 0},"beacon");ec=function(a){var b,c,d,e;d=!1;b=Ya;a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Ra(a));if(a){e=Xc(a);O||(O=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):
Na());c=O;if(e.length>=c.length&&e.substr(0,c.length)===c)return!0;if("msie"===n.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;c=-1!==e.indexOf(c)?e:Nb(a,e);b&&yd(e);fc(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),wb)}return!0};Na=function(){var a;a="msie"===n.browser&&8>=n.version;return!Wc()&&!a?"//go.skimresources.com":"//go.redirectingat.com"};ma=function(a){return-1!==(O||Na()).indexOf(a)||-1!==a.indexOf("go.redirectingat.com")||
-1!==a.indexOf("go.skimresources.com")};Yb=function(a){return!0===w[a]||(null===w[a]||void 0===w[a])&&uc&&!ma(a)};Da=function(a){return oa?(Yb(a)&&(J+=1),!1):Yb(a)};nd=function(a){return a in jb};$b=function(a){var b,c;if(!Bb)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+Bb+"]").toLowerCase();c=td(b);if(!c)return!1;c=c.toLowerCase();c=G(c);b=c.lastIndexOf(a);return-1!==b&&b+a.length===c.length};ka=function(a){return!a||sb&&a===sb||!dd(a)};dd=function(a){var b,c,d,e;if(!a)return!1;
b=a.toLowerCase().split(/\s+/);a=tb?[tb.toLowerCase()]:[];a=a.concat(Gc);for(d=0,e=b.length;d<e;d++)if(c=b[d],0<=sa.call(a,c))return!0;return!1};Mb=function(){var a,b,c,d;S={};ea={};V&&na.push(V);d=na.concat(Hc);for(b=0,c=d.length;b<c;b++)a=d[b],S[a]=a.length;for(b=0,c=Z.length;b<c;b++)a=Z[b],ea[a]=a.length;return S};nb=function(a){var b,c,d;(null===S||null===ea)&&Mb();if(!a)return!1;for(b in S)if(F.call(S,b))if(c=S[b],0===b.indexOf("*")){if(b=b.substr(1),c-=1,d=a.lastIndexOf(b),-1!==d&&d===a.length-
c)return!0}else if(a===b)return!0;return!1};fd=function(a){var b,c,d;(null===S||null===ea)&&Mb();if(!a)return!1;if(0===Z.length)return!0;for(b in ea)if(F.call(ea,b))if(c="*"===b.substr(0,1),d="*"===b.substr(b.length-1,1),b=b.replace(/\*/g,""),c&&d){if(-1!==a.indexOf(b))return!0}else if(c){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(d){if(0===a.indexOf(b))return!0}else if(a===b)return!0;return!1};ja=function(a,b){return Sa(a,b)&&!nb(b)&&fd(b)};hd=function(a,b,c){return"selector_bl"===
b?gd(a,c):!1};gd=function(a,b){return!a&&!b?!1:Boolean(b&&("function"===typeof a.closest?a.closest(b):void 0))};rb=function(a){if(M&&10>a)return Ba=qd(),setTimeout(function(){return rb(a+1)},2E3*a)};qd=function(){var a,b,c,d,e,f,i;if(M){b={};d=[];c=[];for(e=0,f=Ba.length;e<f;e++)a=Ba[e],a.parentNode?c.push(a):b[a.href]=1;i=T();for(e=0,f=i.length;e<f;e++)a=i[e],b[a.href]&&d.push(a);Lb(d,!1);return d.concat(c)}};Kc=function(a,b){var c,d,e;d=[];oa&&(a.xrf=1);for(c in a)F.call(a,c)&&(e=a[c],"data"!==
c&&d.push(""+c+"="+e));a.data&&d.push("data="+a.data);return b+"?"+d.join("&")};ud=function(a){var b,c;b=Ca(a);if(ma(b))return!0;b="";0<a.indexOf("#slm-")&&(c=a.split("#slm-"),2===c.length&&!isNaN(c[1])&&10*parseInt(c[1])===10*c[1]&&(a=c[0],b=c[1]));a={call:"track",data:p('{"pubcode":"'+C+'", "referrer":"'+z+'", "pref":"'+P+'", "site":"'+V+'", "url":"'+a+'", "custom":"'+B+'", "xtz":'+A+', "uuid":"'+H+'", "slmcid":"'+b+'", "product":"1"}')};x&&(a.dnt=x);N&&(a.fdnt=1);a=Kc(a,"//t.skimresources.com/api/");
a=a+"&rnd="+Math.random();Yc(a);return!0};fc=function(a){var b,c;if(!(null!==a&&a.sl_href_restore_scheduled))return b=a.href,c="msie"===n.browser&&7>n.version?1E4:wb,a.sl_href_restore_scheduled=!0,setTimeout(function(){return function(){a.href=b;a.href=b;return delete a.sl_href_restore_scheduled}}(this),c)};cd=function(a,b){var c,d;d=!1;c=sd(b);if(c!==b&&(a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Ra(a)),a)){if("msie"===n.browser&&a.childNodes.length&&3===
a.childNodes[0].nodeType)d=a.innerHTML;fc(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),300)}return c};gc=function(a,b){var c,d;rc(a);E&&l(a,"target",E);d=l(a,"onclick");c="click"===b.type||"contextmenu"===b.type;if(null!=d&&-1!==d.toString().indexOf("return false")){if(c)return ub(a),cc(b)}else return ub(a),L(b)};pb=function(a){var b,c,d;b=kb(a);d=b.href;c=Ca(d);ma(c)&&(d=cd(b,d));""===v&&oc?gc(b,a):ud(d);return!0};Yc=function(a){var b,
c;b=j.getElementsByTagName("body")[0];c=j.createElement("img");c.src=a;c.width=1;c.height=1;if("undefined"!==typeof c.style)c.style.display="none";b.appendChild(c);return c};ha=function(a,b,c,d,e){var t;var f,i,o,g,h;null==c&&(c={});f=c.charset||null;h=c.target||null;t=null!=(i=c.async)?i:!0,c=t;i=null!=h&&h.document?h.document:j;o=i.getElementsByTagName("head")[0];g=i.createElement("script");g.type="text/javascript";if(f)g.charset=f;if(b)g.onload=g.onreadystatechange=function(a){return function(){var c;
c=!1;return function(){var d;d=a.readyState;if(!c&&(!d||"complete"===d||"loaded"===d))return g.onload=g.onreadystatechange=null,c=!0,b.call(h),!0}}}(this)();g.onerror=function(){if(null!=d)return null!=e?d(e):d(!1)};g.async=!1!==c;g.src=a;o.appendChild(g);return g};T=function(a,b){var c,d,e,f,i,o;e=null;a&&(e=RegExp("\\b"+Pa(a)+"\\b","i"));o=[];b||(b=j);d=b.getElementsByTagName("a");for(f=0,i=d.length;f<i;f++){c=d[f];try{c.href&&(!e||c.className&&e.test(c.className))&&o.push(c)}catch(g){}}d=b.getElementsByTagName("area");
for(f=0,i=d.length;f<i;f++){c=d[f];try{c.href&&(!e||c.className&&e.test(c.className))&&o.push(c)}catch(h){}}return o};Ta=function(a){return-1!==a.indexOf("itunes.apple.com")||-1!==a.indexOf("itunes.com")||-1!==a.indexOf("phobos.apple.com")?!0:!1};rc=function(a){var b,c,d;if(!Fa)return!1;for(c in Fa)if(wd(Fa,c)&&(d=Fa[c],(b=l(a,c))&&0===b.indexOf(d)))b=b.substr(d.length),l(a,c,b);return!0};Zb=function(a){return a&&Ab&&!zb&&ia(""+a,Ab)};Jc=function(a){var b,c;c=l(a,"rel");b=K(a.hostname);if(!c&&b&&
!0===w[b])return l(a,"rel","nofollow")};Lb=function(a,b){var c,d,e,f,i,o,g,h,j,k,t;null==b&&(b=!0);f=za.length||Aa.length||ca.length;o=[];d=0;for(k=0,t=a.length;k<t;k++)if(c=a[k],i=K(c.hostname),c.sl_hidden_domain&&(i=K(c.sl_hidden_domain)),j=G(c.href),Sa(j,i)){h=l(c,"rel");g=l(c,"onclick");l(c,"sl-processed",1);c["sl-processed"]=1;e=Wb(j);Zb(e)&&Rb(xb,yb);if(b&&ja(j,i)&&(Da(i)?(d++,q.hasOwnProperty(j)?q[j].ae=1:q[j]={count:0,ae:1}):q.hasOwnProperty(j)||(q[j]={count:0,ae:0}),q[j].count++,e))q[j].slmcid=
e,0>sa.call(W,e)&&W.push(e);J=d;if(!pa||!Ta(j))if((!f||!Ua(c))&&!$b(c))Da(i)||Ta(j)?(q.hasOwnProperty(j)&&(q[j].ae=1),ka(h)&&(rc(c),E&&l(c,"target",E),null!=g&&-1!==g.toString().indexOf("return false")?s(c,"click",cc):s(c,"click",L),Cb(c,!1),mb(c),o.push(c),Za||s(c,"contextmenu",L),ub(c))):Sa(j,i)&&!nb(i)&&ka(h)&&(E&&l(c,"target",E),s(c,"click",pb),Za||s(c,"contextmenu",pb))}return o};cc=function(a){var b;b=kb(a);if(g("_mugicPopWin"))return g("_mugicPopWin")(b);L(a);return(E?h.open(b.href):h.open(b.href,
E)).focus()};mb=function(a,b){var c,d,e,f,i;if(g("link_icon")||0<a.getAttribute("data-skim-product")&&g("skimwords_product_icon")){if(0<a.getElementsByTagName("img").length)return!0;if("msie"===n.browser&&8>n.version)a.style.display="inline-block";d=c="";null!=b&&(c=g("skimwords_icon_class",""),d=g("skimwords_icon_link_class",""));i=l(a,"title").replace("'","&#39;");e=g("link_icon")||g("skimwords_product_icon");f=j.createElement("a");l(f,"href",l(a,"href"));l(f,"title",i);l(f,"style","border:0px;padding:0;margin:0");
l(f,"skimlinked","skimlinked");l(f,"target","_blank");I(a,"skimlinks-unlinked")||I(a,"skimwords-link")?(l(f,"data-skim-creative",Oa(a,"skim-creative")),l(f,"data-group-id",Oa(a,"group-id")),l(f,"data-skimwords-word",Oa(a,"skimwords-word")),l(f,"data-skimwords-id",Oa(a,"skimwords-id")),I(a,"skimlinks-unlinked")?l(f,"class","skimlinks-icon-link "+d+" skimlinks-unlinked"):l(f,"class","skimlinks-icon-link "+d+" skimwords-link")):(l(f,"data-skim-creative",""),l(f,"data-group-id",""),l(f,"data-skimwords-word",
""),l(f,"data-skimwords-id",""),l(f,"class","skimlinks-icon-link "+d));d=j.createElement("img");l(d,"src",e);l(d,"class",c);l(d,"skimlinked","skimlinked");l(d,"style","margin: 0px 0px -3px 2px !important; float:none !important; border:0px; float:none !important; display:inline !important; width: auto !important; height: auto !important;");f.appendChild(d);c=j.createElement("div");c.appendChild=f;c=c.childNodes[0];s(c,"mousedown",L);a.appendChild(f)}return!0};$c=function(a,b){return null!=a.currentStyle?
a.currentStyle[b]:h.getComputedStyle?j.defaultView.getComputedStyle(a,null).getPropertyValue(b):!1};ia=function(a,b){var c,d,e;for(d=0,e=b.length;d<e;d++)if(c=b[d],c===a)return!0;return!1};ic=function(a){var b,c,d,e;h.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(va.push(a),qb.publish("beacon",a));null!=h.skimlinks_runner&&(h.skimlinks_runner.skimlinks=1);a.guid&&""===v&&(v=a.guid);a.sessid&&""===D&&(D=a.sessid);e=a.merchant_domains||[];for(c=0,d=e.length;c<d;c++)b=e[c],ma(b)||
(w[b]=!0);for(b in w)null===w[b]&&(w[b]=!1);if(kc){e=T();for(c=0,d=e.length;c<d;c++)b=e[c],Jc(b)}M&&(b=T(),Ba=Lb(b),J+=Ba.length,!Qa&&"undefined"!==typeof ta&&null!==ta&&null!=y&&null!=y.domains&&(Qa=!0,ta(y.domains)),jc());ra||Ac(a);return!0};rd=function(a){var b,c,d,e;h.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(va.push(a),qb.publish("beacon",a));null!=h.skimlinks_runner&&(h.skimlinks_runner.skimlinks=1);a.guid&&""===v&&(v=a.guid);a.sessid&&""===D&&(D=a.sessid);e=a.merchant_domains||
[];for(c=0,d=e.length;c<d;c++)b=e[c],ma(b)||(w[b]=!0);for(b in w)null===w[b]&&(w[b]=!1);"undefined"!==typeof ua&&null!==ua&&!ra&&ua();"undefined"!==typeof skimwords&&null!==skimwords&&!Ia&&skimwords();return Qb()};Wb=function(a){return-1!==a.indexOf("#slm-")&&(a=a.split("#slm-"),2===a.length&&!isNaN(a[1])&&10*parseInt(a[1])===10*a[1])?parseInt(a[1]):null};Qb=function(a){var b,c,d,e,f,i,o,g;a||(a=0);if(h.skimlinks_requests_in_flight&&5>a)setTimeout(function(){return Qb(a+1)},400*a);else{e=T();c=0;
for(o=0,g=e.length;o<g;o++)if(b=e[o],i=G(b.href),d=K(b.hostname),f=l(b,"class"),(!f||!(-1!==f.indexOf("skimwords-link")||-1!==f.indexOf("skimlinks-unlinked")))&&ja(i,d)&&!hd(b,"selector_bl",Ub))if(b=Wb(i),Zb(b)&&Rb(xb,yb),Da(d)?(c++,q.hasOwnProperty(i)?q[i].ae=1:q[i]={count:0,ae:1}):q.hasOwnProperty(i)||(q[i]={count:0,ae:0}),q[i].count++,b)q[i].slmcid=b,0>sa.call(W,b)&&W.push(b);J=c;!Qa&&"undefined"!==typeof ta&&null!==ta&&null!=y&&null!=y.domains&&(Qa=!0,ta(y.domains));jc()}return!0};jc=function(){"undefined"!==
typeof cb&&null!==cb&&(xc||Ha)&&w.length&&cb();"undefined"!==typeof Ja&&null!==Ja&&Ja("skimlinks");return!0};Rb=function(a,b){var c;if(!a||!b)return!1;zb=!0;h.adroll_adv_id=a;h.adroll_pix_id=b;h.__adroll_loaded=!0;c=j.createElement("script");c.setAttribute("async","true");c.type="text/javascript";c.src="//s.adroll.com/j/roundtrip.js";return j.getElementsByTagName("head").length?j.getElementsByTagName("head")[0].appendChild(c):j.getElementsByTagName("script")[0].parentNode.appendChild(c)};hb=function(){var a,
b,c,d,e,f,i;d=T();c=[];for(f=0,i=d.length;f<i;f++)a=d[f],b=K(a.hostname),e=G(a.href),a=l(a,"rel"),b&&ja(e,b)&&ka(a)&&!ma(b)&&void 0===w[b]&&(c.push(b),y.domains.push(b),w[b]=null);return c};Oc=function(a){return M&&(a=j.getElementById(a))?(s(a,"click",ba),s(a,"contextmenu",ba),!0):!1};Nc=function(a){var b,c,d;if(M&&"function"===typeof j.getElementsByClassName){b=j.getElementsByClassName(a);for(c=0,d=b.length;c<d;c++)a=b[c],s(a,"click",ba),s(a,"contextmenu",ba);return!0}return!1};Mc=function(){var a;
a=j.getElementsByTagName("body");if(0<a.length)return s(a[0],"click",ba),s(a[0],"contextmenu",ba)};ba=function(a){var b,c,d;if(h.event)a=h.event;c=a.originalTarget||a.srcElement||a.target;try{if("A"!==(null!=c?c.nodeName.toUpperCase():void 0)&&c.parentNode)c=Ra(c)}catch(e){c=null}if(!c||Ua(c)||!ka(l(c,"rel")))return!0;try{b=l(c,"sl-processed")||0,null==c["sl-processed"]&&(b=0)}catch(f){b=0}if((d=l(c,"class"))&&(-1!==d.indexOf("skimwords-link")||-1!==d.indexOf("skimlinks-inline")||-1!==d.indexOf("skimlinks-unlinked")))b=
!0;if("A"===(null!=c?c.nodeName.toUpperCase():void 0)&&0===b)if(b=c,c=!0,!b||!b.href?c=!1:0!==b.href.indexOf("http://")&&0!==b.href.indexOf("https://")&&0!==b.href.indexOf("//")&&(c=!1),c&&ja(b.href,K(b.hostname))){ec(b);if(g("vglnk")&&I(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=h.event,a.cancelBubble=!0);return!0}};sc=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return sc(a,b-1,c)}};Zc=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=
sc(function(){return a.parentNode},3,null),null==a)return null;return a};Xc=function(a){var b,c;return bc&&(b=K(a.hostname),b in jb)?(b="[&?]"+jb[b].name+"=(http[^&]+)",decodeURIComponent(null!=(c=a.href)?c.match(RegExp(b)).pop():void 0)||a.href):a.href};jd=function(a){return!a||!a.href||0!==a.href.indexOf("http://")&&0!==a.href.indexOf("https://")&&0!==a.href.indexOf("//")?!1:!0};ed=function(a){if(!pc)return!1;if(null===a.offsetParent||"function"===typeof h.getComputedStyle&&(a=h.getComputedStyle(a),
"hidden"===a.visibility))return!0;return!1};fb=function(a){var b,c,d,e;if(h.event)a=h.event;b=a.originalTarget||a.srcElement||a.target;c=null!=b?b.nodeName.toUpperCase():void 0;"A"!==c&&"AREA"!==c&&(b=Zc(b));if(!b||Ua(b)||!ka(l(b,"rel"))||$b(b))return!0;e=G(b.href);c=K(b.hostname);d="click"===a.type||"contextmenu"===a.type;if(jd(b)&&ja(b.href,c)&&!ed(b)){b.sl_hidden_domain&&(c=K(b.sl_hidden_domain));if(pa&&Ta(e))return!0;if(Da(c)||Ta(e)||nd(c))gc(b,a);else if(d&&Sa(e,c)&&!nb(c))return E&&l(b,"target",
E),pb(a);return!0}};md=function(a,b){var c,d,e,f,i,o;null==b&&(b=mc);h.skimlinks_requests_in_flight=(null!=(c=h.skimlinks_requests_in_flight)?c:0)+1;if(!(null!=a&&a.length))return h[b](),!1;c=p('{"pubcode":"'+C+'","domains":_DOMAIN_LIST_,"page":"'+z.href+'"}');f="//r.skimresources.com/api/?callback="+b+(x?"&dnt="+x:"")+(N?"&fdnt=1":"")+(yc?"&call=toolbar":"")+"&data="+c;c="msie"===n.browser?2E3:8E3;e=[];for(i=0,o=a.length;i<o;i++)d=a[i],e.push(d),f.replace("_DOMAIN_LIST_",p(r(e))).length>c&&(e=e.slice(0,
-1));f=f.replace("_DOMAIN_LIST_",p(r(e)));return ha(f,!1,{})};wa=function(a){var b,c;b=[];oa&&(a.xrf=1);for(c in a)a.hasOwnProperty(c)&&b.push(""+c+"="+p(a[c]));return b.join("&")};Va=function(a,b,c){var d,e,f;if("msie"!==n.browser)e=!1,f=new XMLHttpRequest,f.open("POST",a,!0),f.setRequestHeader("Content-type","application/x-www-form-urlencoded"),0<=sa.call(f,"withCredentials")&&(f.withCredentials=!0),f.async="true",f.onreadystatechange=function(){var a,b;if(e)return!0;if(4===f.readyState){e=!0;if(200===
f.status){a={};b=f.responseText;if(0===b.indexOf("//"))return c(a),!0;if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=JSON.parse(f.responseText)}catch(d){}c(a);return!0}return!1}},f.send(b);else if(h.XDomainRequest){if(d=new XDomainRequest,0<=sa.call(d,"withCredentials")&&(d.withCredentials=!0),d){d.open("POST",a,!0);d.onload=function(){var a;a={};if(0===d.responseText.indexOf("//"))return c(a),!0;if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=JSON.parse(d.responseText)}catch(b){}c(a);
return!0};d.onerror=function(){return!1};d.onprogress=function(){return!1};d.ontimeout=function(){return!1};d.async=!0;try{d.send(b)}catch(i){return!1}}}else return!1;return!0};Wa=function(a,b){var c;c={data:r({pubcode:C,domains:a,page:z.href})};wa(c);md(a,b);return!0};ob=function(a){var b,c,d,e;c=[];for(d=0,e=a.length;d<e;d++)b=a[d],(null===w[b]||void 0===w[b])&&c.push(b);return c.length?Wa(c):!0};dc=function(){var a,b,c,d,e,f;c=T();f=[];for(d=0,e=c.length;d<e;d++)(a=c[d])&&a.href?(b=Ca(a.href),
0>sa.call(Sc,b)?(l(a,"sl-processed",0),f.push(a["sl-processed"]=0)):f.push(void 0)):f.push(void 0);return f};Xb=function(){return"undefined"!==typeof aa&&null!==aa?"function"===typeof aa.init?aa.init(xd,Vc,bd):void 0:void 0};zc=function(){if(h.skimlinksInitialized&&"function"!==typeof post_skimwords_hook)return!0;h.skimlinksInitialized=!0;ac();Xb();pa&&dc();vc&&!qa&&M&&Mc();qa||(hb(),ra&&Wa(y.domains));"undefined"!==typeof ua&&null!==ua&&!ra&&ua();"undefined"!==typeof skimwords&&null!==skimwords&&
!Ia&&skimwords();return!0};kd=function(){if(xa)return!1;xa=!0;return zc()};od=function(a){var b,c;b=0;for(c in a)F.call(a,c)&&(b+=1);return b};Cb=function(a,b){var c,d;d=a.style.cssText;""!==d&&(d+=" ");g("link_background")&&(c=g("link_background"),-1===c.indexOf("#")&&(c="#"+c),d+="background-color: "+c+" !important; ");if(null!==g("link_tooltip",null))a.title=g("link_tooltip");if(b){g("skimwords_color")&&(c=g("skimwords_color"),-1===c.indexOf("#")&&(c="#"+c),d+="color: "+c+" !important; ");g("skimwords_weight")&&
(d+="font-weight: "+g("skimwords_weight")+" !important; ");g("skimwords_decoration")&&(c=g("skimwords_decoration"),d="double"===c?d+"border-bottom: 1px double !important; ":"dashed"===c?d+"border-bottom: 1px dashed !important; ":d+("text-decoration: "+c+" !important; "));g("skimwords_style")&&(c=g("skimwords_style"),d+="font-style: "+c+" !important; ");g("skimwords_link_style")&&(c=g("skimwords_link_style"),d+=c+"; ");c=" "+a.className;if(g("skimwords_link_class"))c+=" "+g("skimwords_link_class"),
a.className=c.substring(1);if(null!==g("skimwords_title",null))a.title=g("skimwords_title");if(null===a.getAttribute("title"))a.title="Shopping link added by SkimWords";if(a.getAttribute("data-skim-creative")&&(c=parseInt(a.getAttribute("data-skim-creative"))%10,1===c||2===c))a.title=""}a.style.cssText=d;return!0};U=function(){return M?kd():Rc()};Qc=function(){var a;h.skimlinksInitialized=!0;Xb();pa&&dc();qa||(a=hb(),Wa(a),lc&&s(j,"mouseup",fb,!0),s(j,"click",fb,!0),s(j,"contextmenu",fb,!0));return ac()};
vd=function(a,b){var c,d,e,f,i;e=!1;if(Eb){d=Uc(a);0===d.length&&(e=!0);for(f=0,i=d.length;f<i;f++)if(c=d[f],0<=c.indexOf(b)){e=!0;break}}return e};Uc=function(a){var b,c,d,e;c=[];for(d=0,e=a.length;d<e;d++)b=a[d],b=b.replace(/https?\:\/\//,""),b=b.split("?")[0],c.push(b.split("#")[0]);return c};ac=function(){var a;a=vd(Eb,location.host+location.pathname);if(wc&&a&&"function"===typeof SkimPageIntelligence)return a="undefined"!==typeof Q&&null!==Q?Q:"//t.skimresources.com/api/",Tb=SkimPageIntelligence({dataCollectionUrl:a+
"dwelltime",pub:C,guid:v,uuid:H,sessid:D}),Tb.start()};Rc=function(){if(xa)return!1;xa=!0;return Wa(hb(),"skimlinksApplySecondaryHandlers")};hc=function(){return function(){return function(){var a,b,c;if(h.skimInitAlreadyCalled)return!1;h.skimInitAlreadyCalled=!0;Lc();ge.detect(function(a){return Y=a});if(g("skimlinks_revenue_forecast")&&g("skimlinks"))return!1;M||Qc();b=function(){if(xa)return!0;try{j.documentElement.doScroll("left")}catch(a){return setTimeout(b,50),!1}return U()};a=function(){return function(){return j.addEventListener?
function(){j.removeEventListener("DOMContentLoaded",a,!1);U();return!0}:j.attachEvent?function(){j.detachEvent("onreadystatechange",a);U();return!0}:function(){U();return!0}}}(this)();if("complete"===j.readyState)setTimeout(U,1);else if(j.addEventListener)j.addEventListener("DOMContentLoaded",a,!1),h.addEventListener("load",U,!1);else if(j.attachEvent){j.attachEvent("onreadystatechange",a);h.attachEvent("onload",U);c=!1;try{c=null===h.frameElement}catch(d){}j.documentElement.doScroll&&c&&b()}return!0}}}(this)();
Pc=function(a,b){return setTimeout(b,a)};null==h.skimlinksApplyHandlers&&(h.skimlinksApplyHandlers=ic);null==h.skimlinksApplySecondaryHandlers&&(h.skimlinksApplySecondaryHandlers=rd);null==h.skimlinksApplyHandlersAlt&&(h.skimlinksApplyHandlersAlt=ic);null==h.skimlinksAjaxHandlerByClass&&(h.skimlinksAjaxHandlerByClass=Nc);null==h.skimlinksAjaxHandlerById&&(h.skimlinksAjaxHandlerById=Oc);null==h.skimlinksRewriteUrl&&(h.skimlinksRewriteUrl=Nb);if(null==h.skim_init)h.skim_init=hc;!g("mugicPopWin")&&!g("skimlinks_legacy_support")&&
!g("skimlinks_revenue_forecast")&&(h.mugicPopWin=L);!g("mugicRight")&&!g("skimlinks_legacy_support")&&!g("skimlinks_revenue_forecast")&&(h.mugicRight=L);h.skimlinksReload=function(){U();return!0};!g("skimlinks_legacy_support")&&!g("skimlinks_revenue_forecast")&&(h.skimlinks=zc);var zd,Ad,Fb,Bc,db,Bd,Cd,Dd,Ed,Fd,Cc,Gb,Gd,Hd,Ka,Id,Jd,X,Dc,F={}.hasOwnProperty;Dc=X=0;db=!1;Bc=function(a){var b;return a&&-1!==a.indexOf("class=")?(b=a.match(/([^\[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a:
a};Dd=function(a){Xa[a]=Xa[a]||0;Xa[a]++;return a+"_"+Xa[a]};Fb=function(a){var b,c,d;b=c=null;-1!==a.indexOf(".")?(a=a.split("."),d=a[0],b=a[1]):-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],c=a[1].split("]"),c=c[0]):d=a;return{tag:d,id:c,"class":b}};Gb=function(a,b){var c,d,e,f,i,g;e=b.split(",");for(i=0,g=e.length;i<g;i++){b=e[i];
b=G(b);b=Fb(b);f=!0;c=(c="string"===typeof a.className?a.className:"")||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";d=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";if(b.tag&&(!a.nodeName||a.nodeName.toLowerCase()!==b.tag))f=!1;if(b["class"]&&(!c||c!==b["class"]&&0!==c.indexOf(b["class"])))f=!1;if(b.id&&(!d||d!==b.id&&-1===d.indexOf(b.id)))f=!1;if(f)return!0}return!1};Cd=function(a){var b,c,d,e,f,i;if("undefined"!==typeof j.querySelectorAll)return j.querySelectorAll(a);
e=[];a=Fb(a);if(a.tag&&a["class"]){d=j.getElementsByTagName(a.tag);for(f=0,i=d.length;f<i;f++)b=d[f],(c=b.className||b.getAttribute("class"))&&0===c.indexOf(a["class"])&&e.push(b)}else a.tag&&a.id?(b=j.getElementById(a.id))&&b.nodeName.toLowerCase()===a.tag&&e.push(b):(a=a.tag,e=j.getElementsByTagName(a));return e};Ed=function(a,b,c){var d,e,f,i,g;d=[];if("undefined"!==typeof a.querySelectorAll)d=a.querySelectorAll(b);else if(b=Fb(b),b.tag&&b["class"]){if(!a.getElementsByTagName)return c?[]:!1;f=
a.getElementsByTagName(b.tag);for(i=0,g=f.length;i<g;i++)if(a=f[i],(e=a.className||a.getAttribute("class"))&&0===e.indexOf(b["class"]))if(c)d.push(a);else return!0}else if(b.tag&&b.id){if((a=j.getElementById(b.id))&&a.nodeName&&a.nodeName.toLowerCase()===b.tag)if(c)d.push(a);else return!0}else b=b.tag,d=a.getElementsByTagName(b);return c?d:0<d.length};Cc=function(a,b){return 0===b.length?!1:Gb(a,b.join(","))?!0:a.parentNode?Cc(a.parentNode,b):!1};Fd=function(a){var b;b=a.offsetWidth;a=a.offsetHeight;
return 468===b&&60===a||234===b&&60===a||728===b&&90===a||300===b&&250===a||250===b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};Bd=function(){var a;a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");a.push("div.ad_container");a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");
-1!==z.href.indexOf(".google.")?(a.push("td.gac_c"),a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):-1!==z.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==z.href.indexOf(".aol.")?(a.push("div.sllLink"),a.push("div.n")):-1!==z.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),
a.push("div.sb_adsWv2"),a.push("div.sb_adsNv2"),a.push("div[class*=sb_ads]"));return a};Hd=function(a){var b,c,d,e;c={};for(d=0,e=a.length;d<e;d++)b=a[d],c[b]=!0;return c};Ka=function(){var a;a={};return{traverse:function(b,c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,f,i,g,h,j,l,k;if(db)return a;db=!0;f=this.get_exclude_selector(c);e=this.get_exclude_selector([]);c=f.selector;f=f.needed;e=e.selector;0===b.length&&b.push("body");
b=b.concat(d);for(h=0,l=b.length;h<l;h++){i=b[h];i=Bc(i);i=Cd(i);for(g=j=0,k=i.length;j<k;g=++j)g=i[g],this.traverse_node(g,f,e,c,d)}return a},traverse_node:function(b,c,d,e,f){var i,g;g=[];i=0;for(g.push({node:b,tagName:"",readOnly:!1,parent_id:null});i<g.length;){if((b=g[i].node)&&!Fd(b)&&!la(b,"noskimwords",!0)&&(!c||!(""!==d&&Gb(b,d)))){g[i].readOnly=!1;if(b.nodeName&&b.nodeName!==ab){g[i].tagName=b.nodeName;if(null!==g[i].parent_id)g[i].readOnly=g[g[i].parent_id].readOnly;if(!g[i].readOnly)if(c&&
Gb(b,e))g[i].readOnly=!0;else if(ia(b.nodeName.toLowerCase(),f))g[i].readOnly=!0;if(ia(b.nodeName.toLowerCase(),f))g[i].readOnly=!0}else if(null!==g[i].parent_id)g[i].tagName=g[g[i].parent_id].tagName,g[i].readOnly=g[g[i].parent_id].readOnly;"msie"===n.browser&&9>n.version&&g[i].readOnly||(b.hasChildNodes()?g=this.add_child_nodes(g[i],i,g):this._add(b,!1,g[i].tagName,g[i].readOnly))}i++}return a},is_traversed:function(){return db},is_good_tag:function(a){return Hd("p,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,section,main".split(","))[a.nodeName.toLowerCase()]?
!0:!1},is_html:function(a){return(a=G(a))&&"<"===a[0]},get_non_colliding_nodes:function(){var b,c,d;d=a;c={};Dc=0;for(b in d)F.call(d,b)&&(c[b]=d[b],Dc++);return c},get_as_hash_node_dict:function(){var b,c,d;c={};for(b in a)d=a[b],a.hasOwnProperty(b)&&(c[b]=d);return c},get_as_pair_array:function(){var b,c;c=[];for(b in a)F.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var d,e,f,g,h,l;g=[];if(!c){c=j.getElementsByTagName("body");if(!c.length)return{needed:!1,selector:""};
c=c[0]}a=a.concat(Bd());for(d=e=0,f=a.length;e<f;d=++e)a[d]=Bc(a[d]);e=!1;f="";for(h=0,l=a.length;h<l;h++)d=a[h],Ed(c,d,!1)&&g.push(d);g.length&&(e=!0,f=g.join(",").replace("class=","class^="));return{needed:e,selector:f}},length:function(){return od(a)},reset:function(){a=[];return db=!1},add_child_nodes:function(a,c,d){var e,f,g,h;h=a.node.childNodes;for(f=0,g=h.length;f<g;f++)(e=h[f])&&e.nodeName&&(this._add(e,!1,a.tagName,a.readOnly)||this.is_good_tag(e)&&d.push({node:e,tagName:a.tagName,readOnly:a.readOnly,
parent_id:c}));return d},add_node:function(a,c){return this._add(a,c)},_add:function(b,c,d,e){var f;f=null;b.nodeName===ab&&(f=G(b.nodeValue));c=c||!1;if("msie"===n.browser&&9>n.version&&e)return!1;if("msie"!==n.browser||9<=n.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(g){}if(f&&!this.is_html(f)&&3<=f.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(f,c);if(!c)return!1;a[c]=b}return f?!0:!1},_skim_id_hash:function(a){var c;if(!a)return"";c=G(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,
"");c=""+c+":"+a.substring(0,20);return c=Dd(c)}}}();Jd=function(a,b,c,d){var e,f,g,h,k,n,R,m,t,u,p;e=j.createDocumentFragment();R=0;m=[];p=b.nodeValue;h=[];k=b.parentNode;d||(d="skimwords-potential");c||(c="-1");if(k){for(t=0,u=a.length;t<u;t++)g=a[t],n=j.createElement("span"),n.className=d,f=j.createTextNode(p.substring(R,g.start)),e.appendChild(f),n.innerHTML=g.text,e.appendChild(n),R={},R.node=n,R.match=g,l(R,"occurrence",g.target_occurrence),m.push(R),R=g.start+g.text.length,h.push(f),Ka.add_node(f,
c);a=j.createTextNode(p.substring(R));h.push(a);e.appendChild(a);Ka.add_node(a,c);k.replaceChild(e,b)}return[m,h]};Ad=function(a,b,c){var d,e,f;if(oa)return!1;d=(a.data?a.data:a.childNodes[0].data).replace(b.repl_regex,b.replacement);f=j.createElement("span");b=j.createDocumentFragment();f.innerHTML=d;if("msie"===n.browser&&9>n.version&&(d=a.previousSibling,e=/^\s/,d&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=" "),(d=a.nextSibling)&&d.nodeValue&&d.nodeValue.length&&
e.test(d.nodeValue[0])))d.nodeValue=" "+d.nodeValue;for(;f.firstChild;)f.firstChild.nodeName===ab?(d=b.appendChild(f.firstChild),Ka.add_node(d)):(d=b.appendChild(f.firstChild),null!==d&&!c&&(Cb(d,!0),mb(d,!0)));if(c=a.parentNode)return c.replaceChild(b,a)};Gd=function(a,b){10>parseInt(b)&&(b="0"+b);return"3"+a+"0"+b};zd=function(a,b){1E7<a&&6!==b&&(a-=1E7);return a};Id=function(a,b,c){var d,e,f;f=b.phrase;d={};d.w=f.text();d.lp=f.url();if(c)d.t=Ec,e="unlinked";else{if(0===f.limit())return!1;f.dec_limit();
X+=1;d.ed=f.is_editor()?1:0;d.t=Gd("02",f.action_type(),f.group_id());e="skimwords";d.pid=0===f.group_id()?0:zd(f.id(),f.action_type())}Kd(d,e);Ad(a,b,c);return!0};if("function"!==typeof Element.prototype.matches)Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||function(a){var b,a=(this.document||this.ownerDocument).querySelectorAll(a);for(b=0;a[b]&&a[b]!==this;)++b;return Boolean(a[b])};if("function"!==typeof Element.prototype.closest)Element.prototype.closest=
function(a){var b;for(b=this;b&&1===b.nodeType;){if(b.matches(a))return b;b=b.parentNode}return null};var Ld,Md,Nd,Od,Pd,Qd,Ac,Rd,ua,Ec;Ec="500005";Md=function(a){s(a,"click",L);Za||s(a,"contextmenu",L);Cb(a,!1);return mb(a)};Qd=function(a){a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig.exec(a);return a.length&&""!==a[0]?!0:!1};Od=function(a,b,c,d){var e,f;e=Pa(a);f="";E&&(f='target="'+E+'"');b=lb(b);e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+
e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a='$1$2<a href="'+b+'" class="'+d+'" '+f+' data-skimwords-word="'+encodeURIComponent(lb(a))+('"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6');b=e.replace(/\?:/g,"");return{search_regex:RegExp(e,"i"),repl_regex:RegExp(b,"i"),repl_text:a}};Ld=function(){var a,b,c,d,e;b=T("skimlinks-unlinked");e=[];for(c=0,d=b.length;c<d;c++)a=b[c],e.push(Md(a));return e};Ac=function(a){var b,c,d,e;b={};if((c=a.merchant_domains)&&c.length){for(d=0,
e=c.length;d<e;d++)a=c[d],b[a]=!0;for(d=0,e=Db.length;d<e;d++)c=Db[d],a=c.match.domain,b.hasOwnProperty(a)&&Id(c.node,c.match,!0)}Pc(10,function(){return Ld("skimlinks-unlinked")});try{return Ja("unlinked")}catch(f){return!0}};Nd=function(a,b){var c,d,e,f,g,h,j,l,k,m,t;if(!a||Cc(a,["span.skimlinks-unlinked"]))return[[],[]];t=a.data;e=[];h=[];for(k=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig;d=k.exec(t);)if(c=d[0],"link.phrase"!==c)if(g=d.index,0<G(c).length&&
-1===c.indexOf("/.")&&-1===c.indexOf("..."))f=c,0!==c.indexOf("http")&&0!==c.indexOf("//")&&(f="msie"===n.browser&&6>=n.version?"http://"+c:"//"+c),d=Ca(f),l=Sd({OriginalPhrase:""+c,Url:f,Title:"",ActionType:2,GroupId:0,Unlinked:!0}),(m=Od(""+c,f,Ec,"skimlinks-unlinked"))&&h.push({start:g,text:""+lb(c),domain:d,repl_regex:m.repl_regex,replacement:m.repl_text,regex:m.search_regex,phrase:l,link:f}),e.push(d);else break;if(h.length){j=Jd(h,a,b,"skimlinks-unlinked");c=j[0];j=j[1];for(k=0,t=c.length;k<
t;k++)h=c[k],Db.push(h)}j||(j=[]);return[e,j]};Rd=function(a){var b,c,d;if(na.length)for(c=0,d=na.length;c<d;c++)if(b=na[c],b===a)return!1;if(Z.length){for(c=0,d=Z.length;c<d;c++)if(b=Z[c],b===a)return!0;return!1}return!0};Pd=function(){var a,b,c,d,e,f,g;c=Ka.get_as_hash_node_dict();d={};for(b in c)if(a=c[b],a.parentNode&&!Ua(a)&&!la(a,"noskimwords")&&!la(a,"noskimlinks")&&!la(a,"noskimw")&&(!a.meta||!a.meta.ReadOnly)){a=Nd(a,b);g=a[0];for(e=0,f=g.length;e<f;e++)a=g[e],!d[a]&&Rd(a)&&(d[a]=!0,y.domains.push(a))}return y.domains.length?
ob(y.domains):Ja("unlinked")};ua=function(){var a;a=j.getElementsByTagName("body");a.length?(a=a[0].textContent||a[0].innerText)&&Qd(a)?Ia?(Ka.traverse([],tc,[]),Pd()):getSkimwordsData("skimwordsSettingsCallback"):y.domains.length&&ob(y.domains):y.domains.length&&ob(y.domains)};h.skimlinksUnlinked=Ac;var Td,Hb,Ud,Vd,m,La,Wd,Ib,Xd,Yd,Zd,$d,ae,cb,be,F={}.hasOwnProperty;m={pag:"",pub:"",guid:"",uc:"",lnks:{}};La={};Vd=function(a,b){var c,d,e;e="GBP"===a.currency?"&pound;":"EUR"===a.currency?"&euro;":
"$";d=j.createElement("a");l(d,"href",a.url);l(d,"title",a.title);l(d,"target","_blank");Ic(d,"skimlinks-inline");l(d,"data-skim-creative",b);c=0;Ha&&(c=1);l(d,"data-skimlinks-editor",c);c=parseFloat(Math.round(100*a.price)/100).toFixed(2);d.innerHTML=""+a.merchant+" "+e+c;s(d,"mousedown",L);return d};Ud=function(a,b,c,d,e){return"8"+("text"===a?"1":"cross"===a?"2":"blink"===a?"3":"0")+b+c+(d-1)+e};Wd=function(a,b){var c,d,e,f,g,h,j;c=b.price;if(!c)return"0";d=0;e=1E8;g=0;for(h=0,j=a.length;h<j;h++)f=
a[h],f=parseFloat(f.price),f>d&&(d=f),parseFloat(f)<e&&(e=f),f===c&&g++;return 1<g?"4":c>=d?"3":c<=e?"1":"2"};be=function(a,b,c){var d,e,f,g,h;e=!1;for(d=g=0,h=a.length;g<h;d=++g)if(f=a[d],f.url===c){e=d;break}e&&(c=a[e],"beginning"===b?(a[e]=a[0],a[0]=c):"end"===b&&(a[e]=a[a.length-1],a[a.length-1]=c));return a};ae=function(a){var b,c;if("1"===l(a,"ipc-added")){for(;")"!==(null!=(c=a.nextSibling)?c.textContent.substring(0,1):void 0);)(b=a.nextSibling)&&b.parentNode&&b.parentNode.removeChild(b);if(a&&
a.parentNode&&a.nextSibling)return a.parentNode.removeChild(a.nextSibling)}};Td=function(a,b,c,d,e,f,g){var o,k,m,n,p,t,u,q,r,s,w,v,x,y;ae(b);m=!0;p=b;n=!1;c=be(c,qc,d);e.hasOwnProperty(d)?(t=e[d],f[t].cnt++):(g[d]={},t={},t.lpid=d,t.cnt=1,t.url=b.href.replace(ya,""),t.prd=[],t.ed=Ha?1:0,f.push(t),t=f.length-1,e[d]=t);"cross"===Ea?l(b,"style","text-decoration: line-through !important;"):"text"===Ea?null!=b.parentNode&&(e=null!=(q=$c(b.parentNode,"color"))?q:"#000",l(b,"style","color: "+e+" !important; text-decoration: none !important;")):
"blink"===Ea&&l(b,"style","text-decoration: blink !important;");e=c.length;q=0;if(h.skimlinks_editor)x=b.parentNode,v=j.createElement("span"),w=j.createElement("span"),o=b.cloneNode(!0),v.appendChild(o),v.appendChild(w),v.style.display="inline !important",v.classList.add("sl-select-wrapper"),w.classList.add("sl-select-products"),o.classList.add("sl-select-link");for(o=0,y=c.length;o<y;o++){u=c[o];n=!0;s=u.currency+u.price+u.url+u.title+u.merchant;q+=1;k=Wd(c,u);k=Ud(Ea,k,e,a,q);if(!g[d].hasOwnProperty(s))r=
{},r.cur=u.currency,r.mn=u.merchant,r.mid=u.merchant_id,r.pr=u.price,r.ti=u.title,r.pu=u.url.replace(ya,""),r.cr=k,f[t].prd.push(r),g[d][s]=!0;u=Vd(u,k);m?(s=j.createTextNode(" ("),m=!1):s=j.createTextNode(" | ");h.skimlinks_editor?(w.appendChild(s),w.appendChild(u)):(p.parentNode.insertBefore(s,p.nextSibling),s.parentNode.insertBefore(u,s.nextSibling));p=u}h.skimlinks_editor&&x.replaceChild(v,b);m||(a=j.createTextNode(") "),p.parentNode.insertBefore(a,p.nextSibling));l(b,"ipc-added",1);return n};
Yd=function(a,b,c){var d,e;for(e in b)if(F.call(b,e)&&(d=b[e],e===a&&(0===d.length||ia(c,d))))return!0;return!1};Hb=function(a){var b,c,d,e,f,g,h,j,k,m,n;if(!a)return!1;d={};e=[];g={};c=[];j=!1;for(k in a)if(F.call(a,k)&&La.hasOwnProperty(k)&&(h=a[k],h.length)){f=La[k];for(m=0,n=f.length;m<n;m++)b=f[m],k=G(b.href),l(b,"rel"),Td(1,b,h,k,d,e,g)&&(j=!0),c.push({url:k,occurrence:l(b,"data-occurrence"),products:h})}j&&"undefined"!==typeof Jb&&null!==Jb&&Jb(e);"undefined"!==typeof setSelectLinks&&null!==
setSelectLinks&&setSelectLinks(c);return!0};Xd=function(){var a;a="//ipc.skimresources.com/api/select_whitelist.php?callback=selectWhitelistCallback&data="+p(r({pubcode:C,page:z.href}));return ha(a,!1,{},Ib,[])};Zd=function(a){var b,c,d,e,f,g;e="//ipc.skimresources.com/api/select.php?callback=selectCallback&urls=";b="msie"===n.browser?2E3:8E3;c=[];for(f=0,g=a.length;f<g;f++)d=a[f],c.push(d),d=p(r(c)).length,d+e.length>b&&(c=c.slice(0,-1));if(c.length)return e+=p(r(c)),ha(e,!1,{},Hb,!1)};$d=function(a){var b;
b={urls:r(a),debug:1};b=wa(b);(Y||!Va("//ipc.skimresources.com/api/select.php",b,Hb))&&Zd(a);return!0};Ib=function(a){var b,c,d,e,f,g,h,j,k,m,n,p,q,r,s;if(!1!==a&&0===a.length)return!1;n=[];g={};h=T();k=0;for(p=0,r=h.length;p<r;p++)if(b=h[p],e=K(b.hostname),m=G(b.href),j=l(b,"rel"),d=b.childNodes,!vb.length||ia(e,vb)){if(d&&d.length){f=!1;for(q=0,s=d.length;q<s;q++)c=d[q],c.nodeName&&"IMG"===c.nodeName.toUpperCase()&&(f=!0);if(f)continue}if(ja(m,e)&&ka(j)&&Da(e)&&(g.hasOwnProperty(m)||(g[m]=0),g[m]++,
l(b,"data-occurrence",g[m]),l(b,"data-select-id",k),k++,!a||Yd(m,a,g[m])))if(c=l(b,"class"),!c||!(-1!==c.indexOf("skimlinks-inline")||-1!==c.indexOf("skimwords-link")))if("undefined"===typeof La[m]&&(La[m]=[]),La[m].push(b),ia(m,n)||n.push(m),100<=n.length)break}return 0===n.length?!1:$d(n)};cb=function(){return Ha?Xd():Ib(!1)};h.selectCallback=Hb;h.selectWhitelistCallback=Ib;h.skimlinksApplySelect=cb;var Sd;Sd=function(a){var b,c,d,e;d=b=null;c=5;a.Limit&&(c=a.Limit);e=function(){return a.Priority||
0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return c-1},limit:function(){return c},action_type:function(){return a.ActionType},text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},is_editor:function(){return null!=a.ValidOn&&""!==a.ValidOn?!0:!1},is_blacklisted:function(){return null!=a.IsBlacklisted?a.IsBlacklisted:!1},group_priority:function(){return b?b.group_priority():e()},
id:function(){return d?d:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?"":null!=a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){return a.Unlinked?a.Title="":a.Title=b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=a},set_id:function(a){return d=a}}};var Kd,eb,ce,k,$,Q,Fc,de,ee,fe,yd,Ja,Jb,ta,Kb,Ma,F={}.hasOwnProperty;Q="//t.skimresources.com/api/";k={pag:"",phr:[],unl:[],pub:"",
slc:0,swc:0,ulc:0,jsl:0,jsf:"",guid:"",uuid:"",sessid:"",uc:"",t:1,slmcid:!1};$={skimlinks:!0,skimwords:!0,unlinked:!0};Ma=0;Fc=!1;Kd=function(a,b){var c,d,e,f;c=!0;if("skimwords"===b){for(e=0,f=fa.length;e<f;e++)if(d=fa[e],c=d.pid?d.pid===a.pid:d.w===a.w)return c;fa.push(a)}else if("unlinked"===b){for(e=0,f=ga.length;e<f;e++)d=ga[e],d.w===a.w&&(c=!1);c&&ga.push(a);Ma++}return c};ee=function(){var a,b,c,d,e,f;a=8E3;"msie"===n.browser&&(a=2E3);d={};d.guid=v;d.uuid=H;d.sessid=D;d.pub=C;d.pag=z.href;
d.tz=A;d.slmcid=W;d.dl={};d.typ="l";d.hae=J?1:0;c=""+Q+"link?data=";f=0;for(e in q)F.call(q,e)&&(b=q[e],f++,d.dl[e]=b,b=c+p(r(d)),b.length>a&&(f--,delete d.dl[e]));f&&(c+=p(r(d)),ha(c,!1,{async:!0}));return!0};ta=function(){var a;if(bb)return!1;a={};a.guid=v;a.uuid=H;a.sessid=D;a.pub=C;a.pag=z.href;a.dl=q;a.tz=A;a.slmcid=W;a.typ="l";a.hae=J?1:0;a={data:r(a)};x&&(a.dnt=x);N&&(a.fdnt=1);a=wa(a);if(Y||!Va(""+Q+"link",a,Kb))return ee()};yd=function(a){var b,c,d;b=g("pageTracker");d=g("urchinTracker");
c="/"+$a+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(c),!0;if(d)return d(c),!0;g("_gaq")?(b=g("_gaq"),b.push(["_trackEvent",$a,"click",a])):g("ga")&&g("ga")("send","event","click",$a,a);return!1};de=function(a){var b,c,d,e,f;m.tz=A;m.guid=v;m.uuid=H;m.sessid=D;m.pref=P;m.lnks=[];m.typ="s";b=8E3;"msie"===n.browser&&(b=2E3);c=""+Q+"ipc?data=";for(e=0,f=a.length;e<f;e++)d=a[e],m.lnks.push(d),d=c+p(r(m)),d.length>b&&(m.lnks=m.lnks.slice(0,-1));m.lnks.length&&(c+=p(r(m)),ha(c,!1,{async:!0}));
return!0};Jb=function(a){var b;if(bb)return!1;m.tz=A;m.guid=v;m.uuid=H;m.sessid=D;m.pref=P;m.lnks=a;m.typ="s";b={data:r(m)};b=wa(b);(Y||!Va(""+Q+"ipc",b,Kb))&&de(a);return!0};Kb=function(){return!0};Ja=function(a){var b,c;if(bb||Fc)return!1;$[a]=!1;a=!0;for(b in $)if(F.call($,b)&&(c=$[b],!0===c)){a=!1;break}if(a)return Fc=!0,ce()};eb=function(a){var b,c,d,e,f;if(a instanceof Array){c={};for(b=e=0,f=a.length;e<f;b=++e)d=a[b],c[""+b]=d;return c}return a};fe=function(){var a,b,c,d,e;a=(new Date).getTime()-
Vb;b=8E3;"msie"===n.browser&&(b=2E3);k.tz=A;k.slc=J;k.swc="undefined"!==typeof X&&null!==X?X:0;k.ulc=null!=Ma?Ma:0;k.jsl=a;k.guid=v;k.slmcid=W;k.uuid=H;k.sessid=D;k.pref=P;k.phr=[];k.unl=[];oa&&(k.xrf=1);a=""+Q+"track.php?";x&&(a=a+"dnt="+x+"&");N&&(a+="fdnt=1&");Y&&(a+="abp=1&");a+="data=";for(c=d=0,e=fa.length;d<e;c=++d)c=fa[c],k.phr.push(c),c=a+p(r(k).replace(ya,"")),c.length>b&&(k.phr=k.phr.slice(0,-1));for(c=d=0,e=ga.length;d<e;c=++d)c=ga[c],k.unl.push(c),c=a+p(r(k).replace(ya,"")),c.length>
b&&(k.unl=k.unl.slice(0,-1));k.phr=eb(k.phr);k.unl=eb(k.unl);b=a+p(r(k).replace(ya,""));ha(b,!1,{async:!0});return rb(1)};ce=function(){var a;a=(new Date).getTime()-Vb;k.tz=A;k.slc=J;k.swc="undefined"!==typeof X&&null!==X?X:0;k.ulc=null!=Ma?Ma:0;k.jsl=a;k.guid=v;k.slmcid=W;k.uuid=H;k.sessid=D;k.pref=P;a=k;a.phr=eb(fa);a.unl=eb(ga);a={data:r(a)};x&&(a.dnt=x);N&&(a.fdnt=1);a=wa(a);if(Y||!Va(""+Q+"track.php",a,Kb))return fe(),!0;null!=h.skimlinks_runner&&(h.skimlinks_runner.tracking=1);rb(1);return!0};
var ge=new function(a){function b(a,c){e||1E3<c?"function"==typeof a&&(e?d?a(!0):a(!1):a(!1)):setTimeout(b,c*=2,a,c)}function c(){e||(f.complete&&g.complete&&(e=!0),e&&"0"!=f.width&&"0"==g.width&&(d=!0))}var d=!1,e=!1,f=null,g=null;this.detect=function(h){a:{try{var j=navigator.userAgent.toLowerCase();if(-1==j.indexOf("firefox")&&-1==j.indexOf("chrome")){e=!0;d=!1;break a}}catch(k){}j=11*Math.random();f=new Image;f.onload=c;f.src=a.replace(/\*/,1).replace(/\*/,j);g=new Image;g.onload=c;g.src=a.replace(/\*/,
2).replace(/\*/,j)}b(h,250)}}("//p.skimresources.com/px.gif?ch=*&rn=*");hc()})(this);
